<?php declare(strict_types=1);

/**
 * @return array<string, mixed>
 */
function getPortalData(): array
{
    return [
        'site' => [
            'title' => 'MyAgri - Landwirtschaft in der Wallonie verständlich erklärt',
            'subtitle' => 'Ein Bürgerportal, das landwirtschaftliche Themen der Wallonie in praktische, überprüfbare und kontextbezogene Orientierung übersetzt: Sektoren, Berufe, Jahreszeiten, Labels, Regionen und Ernährungsentscheidungen.',
            'updated_at' => '27. Juni 2026',
            'geo' => [
                'name' => 'Wallonie, Belgien',
                'region' => 'Wallonie',
                'region_code' => 'BE-WAL',
                'country' => 'Belgien',
                'country_code' => 'BE',
                'locality' => 'Namur',
                'latitude' => '50.5039',
                'longitude' => '4.4699',
            ],
        ],
        'quickFacts' => [
            [
                'title' => 'Ein Alltagsthema',
                'content' => 'Hinter jeder Mahlzeit stehen Entscheidungen zu Boden, Wetter, Arbeit, Lagerung und Verteilung. Wer diese Schritte kennt, kann Preise besser einordnen als nur über den Kassenbon.',
            ],
            [
                'title' => 'Eine territoriale Rolle',
                'content' => 'Ein Hof bewirtschaftet nicht nur Fläche. Er prägt Wege, Wiesen, Hecken, Arbeitsplätze und Beziehungen zu Gemeinden, Nachbarn und Wertschöpfungsketten.',
            ],
            [
                'title' => 'Ein Sektor im Wandel',
                'content' => 'Betriebe müssen zwischen Trockenheit, Energie, Investitionen, Regeln, Hofübergabe und Nachfrage abwägen. Selten gibt es dafür nur eine einzige Lösung.',
            ],
            [
                'title' => 'Ein Innovationsfeld',
                'content' => 'Innovation kann digital, agronomisch oder kooperativ sein: Sensoren, angepasste Sorten, Verarbeitungsgemeinschaften oder neue Fruchtfolgen verändern Entscheidungen auf dem Feld.',
            ],
            [
                'title' => 'Ein sozialer Bezug',
                'content' => 'Märkte, Kantinen, Hofbesuche und Einkaufsgemeinschaften schaffen Gelegenheiten für bessere Fragen zu Herkunft, Saison, Vergütung, Haltbarkeit und betrieblichen Zwängen.',
            ],
        ],
        'editorialPrinciples' => [
            [
                'title' => 'Neu formulieren statt kopieren',
                'content' => 'Institutionelle Definitionen dienen als Ausgangspunkt. MyAgri formuliert sie mit lokalen Beispielen, Grenzen und Prüffragen neu.',
            ],
            [
                'title' => 'Fakten, Rat und Meinung trennen',
                'content' => 'Eine nützliche Seite unterscheidet Beobachtbares, praktische Empfehlungen und Informationen, die bei einer zuständigen Stelle bestätigt werden müssen.',
            ],
            [
                'title' => 'Slogans vermeiden',
                'content' => 'Lokal, nachhaltig, biologisch oder kurze Lieferkette sind keine absoluten Garantien. Jeder Begriff wird in Produktions-, Kosten- und Kontrollkontext gestellt.',
            ],
            [
                'title' => 'Quellen sinnvoll nutzen',
                'content' => 'Dossiers behalten hilfreiche Referenzen, liefern aber eine eigene pädagogische Einordnung statt Quellen einfach zu übernehmen.',
            ],
        ],
        'pillars' => [
            ['name' => 'Produzieren', 'description' => 'Ein regelmäßiges Lebensmittelangebot sichern und dabei Saison, Arbeit, Material und Absatzwege berücksichtigen.'],
            ['name' => 'Erhalten', 'description' => 'Wasser, Böden, Klima und Biodiversität als Produktionsgrundlagen behandeln, nicht als getrennte Nebenthemen.'],
            ['name' => 'Verbinden', 'description' => 'Schritte zwischen Feld, Werkstatt, Transport, Geschäft, Kantine und Teller sichtbar machen.'],
            ['name' => 'Erneuern', 'description' => 'Werkzeuge, Praktiken und Kooperationen testen, ihre Wirkungen messen und erst dann ausweiten.'],
        ],
        'sectors' => [
            [
                'label' => 'Ackerbau',
                'emoji' => 'AG',
                'summary' => 'Getreide, Kartoffeln und Zuckerrüben spielen in der Wallonie eine wichtige Rolle.',
                'enjeux' => [
                    'Klimarisiken und Ertragsschwankungen steuern.',
                    'Bodenfruchtbarkeit und Fruchtfolgen sichern.',
                    'Wirtschaftliche Stabilität der Betriebe stärken.',
                    'Wasserverfügbarkeit und Betriebsmittel gezielt einsetzen.',
                ],
                'public_actions' => [
                    'Saisonalität und regionale Herkunft berücksichtigen.',
                    'Regionale Verarbeitungswege kennenlernen.',
                    'Lebensmittelverschwendung verringern, damit landwirtschaftliche Arbeit besser genutzt wird.',
                ],
            ],
            [
                'label' => 'Rinder- und Milchhaltung',
                'emoji' => 'VI',
                'summary' => 'Tierhaltung verwertet Grünland und versorgt Milch- und Fleischketten.',
                'enjeux' => [
                    'Tierwohl und Einkommen der Betriebe sichern.',
                    'Futterautonomie und Produktionskosten steuern.',
                    'Umweltwirkungen senken und Grünland erhalten.',
                    'Hofübergaben und Generationenwechsel vorbereiten.',
                ],
                'public_actions' => [
                    'Labels und Qualitätsansätze prüfen.',
                    'Hofläden und Direktverkäufe unterstützen.',
                    'Herkunft von Milch- und Fleischprodukten vergleichen.',
                ],
            ],
            [
                'label' => 'Gemüsebau, Gartenbau und Obst',
                'emoji' => 'GE',
                'summary' => 'Nahe Produktionen, die gut zu kurzen Lieferketten passen.',
                'enjeux' => [
                    'Arbeitskräfte, Lagerung und Logistik organisieren.',
                    'Bewässerung und Anpassung an Hitze verbessern.',
                    'Direktverkauf wirtschaftlich tragfähig machen.',
                    'Zugang zu geeigneten Flächen sichern.',
                ],
                'public_actions' => [
                    'Direkt bei Produzenten einkaufen, wenn es zum Alltag passt.',
                    'Den Einkaufskorb mit saisonalen Produkten diversifizieren.',
                    'Wochenmenüs planen, damit lokaler Konsum regelmäßig möglich bleibt.',
                ],
            ],
            [
                'label' => 'Diversifizierung: Beeren, Hopfen, Weinbau',
                'emoji' => 'DI',
                'summary' => 'Entstehende Sektoren schaffen lokalen Wert und stärken die Resilienz von Betrieben.',
                'enjeux' => [
                    'Anfangsinvestitionen und technische Begleitung sichern.',
                    'Lokale und touristische Absatzwege strukturieren.',
                    'Sanitäre und klimatische Risiken kontrollieren.',
                    'Kompetenzen in Verarbeitung und Vermarktung aufbauen.',
                ],
                'public_actions' => [
                    'Regionale verarbeitete Produkte entdecken.',
                    'Betriebe besuchen, die Werkstätten für die Öffentlichkeit öffnen.',
                    'Lebensmittelgeschenke aus regionaler Produktion wählen.',
                ],
            ],
        ],
        'focusThemes' => [
            ['title' => 'Wasser', 'details' => 'Wasser sparen, besser speichern und für Kulturen verfügbar halten.'],
            ['title' => 'Böden', 'details' => 'Organische Substanz stärken und Erosion begrenzen.'],
            ['title' => 'Biodiversität', 'details' => 'Hecken, Blühstreifen und ökologische Infrastrukturen sinnvoll einsetzen.'],
            ['title' => 'Klima', 'details' => 'Praktiken anpassen und Emissionen begrenzen.'],
            ['title' => 'Energie', 'details' => 'Kosten durch Effizienz und eigene Erzeugung senken.'],
            ['title' => 'Digitales', 'details' => 'Kulturen und Herden mit verlässlichen Felddaten besser steuern.'],
        ],
        'provinces' => [
            ['name' => 'Wallonisch-Brabant', 'profile' => 'Mosaik aus Ackerbau, Gemüsebau und lokaler Verarbeitung nahe großer Konsumräume.'],
            ['name' => 'Hennegau', 'profile' => 'Starker Ackerbau und Agrarlebensmittelbereich, unterstützt durch wichtige Logistikinfrastruktur.'],
            ['name' => 'Lüttich', 'profile' => 'Tierhaltung, Obst und regionale Verwertung mit dynamischen Initiativen in kurzen Lieferketten.'],
            ['name' => 'Luxemburg', 'profile' => 'Grünland, Wälder und extensive Tierhaltung in Landschaften, in denen Produktion und Natur eng verbunden sind.'],
            ['name' => 'Namur', 'profile' => 'Vielfältige Produktionen zwischen Ackerbau, Tierhaltung und Gemüsebau mit vielen Familienbetrieben.'],
        ],
        'seasonalCalendar' => [
            ['season' => 'Frühling', 'focus' => 'Aussaat, Wassermanagement, Schutz vor Spätfrost und erste Ernteorganisation.'],
            ['season' => 'Sommer', 'focus' => 'Frühe Ernten, gezielte Bewässerung, Wasserstress vermeiden und Arbeitsspitzen steuern.'],
            ['season' => 'Herbst', 'focus' => 'Haupternten, Herbstaussaat, Zwischenfrüchte und Bodenvorbereitung für den Winter.'],
            ['season' => 'Winter', 'focus' => 'Maschinenpflege, Planung, Tierbetreuung und Vorbereitung der nächsten Saison.'],
        ],
        'faq' => [
            ['q' => 'Warum sind Agrarpreise manchmal instabil?', 'a' => 'Sie hängen von Weltmärkten, Wetter, Energie, Verarbeitungskosten und Absatzwegen ab.'],
            ['q' => 'Ist eine kurze Lieferkette immer möglich?', 'a' => 'Nicht für jedes Produkt. Gut organisiert kann sie aber lokale Beziehungen und Wertschöpfung stärken.'],
            ['q' => 'Wie lassen sich Kinder sensibilisieren?', 'a' => 'Durch Hofbesuche, Lebensmittelworkshops, Schulgärten und die Beobachtung der Jahreszeiten.'],
            ['q' => 'Warum ist Ernährungssouveränität ein Thema?', 'a' => 'Sie beschreibt die Fähigkeit eines Gebiets, einen bedeutenden Teil seiner Ernährung auch in Krisen zu sichern.'],
            ['q' => 'Was bedeutet ein fairer Preis für einen Betrieb?', 'a' => 'Ein Preis, der Produktionskosten deckt, Arbeit vergütet und Investitionen in den Wandel ermöglicht.'],
            ['q' => 'Wie kann man handeln, ohne das Budget stark zu erhöhen?', 'a' => 'Saisonal einkaufen, Grundprodukte kochen, Verschwendung senken und lokale Verkaufsstellen vergleichen.'],
            ['q' => 'Warum ist lokal nicht automatisch teurer?', 'a' => 'Der Preis hängt von Produkt, Saison, Verkaufsform, Menge und vermiedener Verschwendung ab. Der Kilopreis und die Mahlzeitenplanung helfen beim Vergleich.'],
            ['q' => 'Wie prüft man landwirtschaftliche Informationen?', 'a' => 'Man unterscheidet Erfahrungsbericht, offizielle Daten, Verkaufsargument und technischen Rat. Für administrative, gesundheitliche oder finanzielle Entscheidungen sollte die zuständige Stelle bestätigen.'],
            ['q' => 'Was ist der Unterschied zwischen lokaler Herkunft und lokaler Verarbeitung?', 'a' => 'Herkunft beschreibt, wo der Rohstoff erzeugt wurde. Verarbeitung beschreibt, wo er vorbereitet, verpackt oder gekocht wurde. Beides ist relevant.'],
            ['q' => 'Warum unterscheiden sich Praktiken je nach Region?', 'a' => 'Technische Entscheidungen hängen von Klima, Boden, Relief, vorhandenen Sektoren und lokalen Absatzwegen ab.'],
        ],
        'glossary' => [
            ['slug' => 'agriculture-biologique', 'term' => 'Ökologische Landwirtschaft', 'definition' => 'Zertifiziertes System, das Pflanzenbau und Tierhaltung regelt, synthetische Mittel stark begrenzt und kontrollierte Rückverfolgbarkeit verlangt.'],
            ['slug' => 'agriculture-de-precision', 'term' => 'Präzisionslandwirtschaft', 'definition' => 'Steuerung von Parzellen oder Herden mit Felddaten, um Mengen, Durchgänge, Warnungen und Eingriffe genauer anzupassen.'],
            ['slug' => 'agriculture-integree', 'term' => 'Integrierte Landwirtschaft', 'definition' => 'Ansatz, der Beobachtung, Prävention und den richtigen Eingriffszeitpunkt vor schweren Maßnahmen priorisiert.'],
            ['slug' => 'agriculture-regeneratrice', 'term' => 'Regenerative Landwirtschaft', 'definition' => 'Praktiken, die Bodenfunktion, Pflanzendecke, nützliche Biodiversität und Widerstandsfähigkeit von Betrieben verbessern sollen.'],
            ['slug' => 'agriculture-urbaine', 'term' => 'Urbane Landwirtschaft', 'definition' => 'Lebensmittelaktivitäten in oder am Rand der Stadt mit Funktionen wie Produktion, Bildung, Integration oder Begrünung.'],
            ['slug' => 'agroecologie', 'term' => 'Agroökologie', 'definition' => 'Betriebsverständnis, das Produktion, biologische Gleichgewichte, Autonomie, Vielfalt und Anpassung an den Ort verbindet.'],
            ['slug' => 'agroforesterie', 'term' => 'Agroforstwirtschaft', 'definition' => 'Kombination von Bäumen mit Kulturen oder Tierhaltung auf derselben Fläche zur Stärkung von Ökosystemleistungen.'],
            ['slug' => 'aop-igp', 'term' => 'g.U./g.g.A.', 'definition' => 'Europäische Herkunftszeichen, die Produkte mit einem Gebiet und einem Pflichtenheft verbinden.'],
            ['slug' => 'assolement', 'term' => 'Anbauverteilung', 'definition' => 'Verteilung der Kulturen auf die Parzellen eines Betriebs in einer Saison.'],
            ['slug' => 'autonomie-fourragere', 'term' => 'Futterautonomie', 'definition' => 'Fähigkeit eines Tierhaltungsbetriebs, den Großteil des Futters selbst zu erzeugen.'],
            ['slug' => 'autonomie-proteique', 'term' => 'Protein-Autonomie', 'definition' => 'Fähigkeit eines Betriebs oder Gebiets, einen wichtigen Teil der benötigten Proteine selbst zu erzeugen.'],
            ['slug' => 'auxiliaires-de-culture', 'term' => 'Nützlinge im Pflanzenbau', 'definition' => 'Organismen wie Insekten, Vögel oder Mikroorganismen, die Bestäubung oder Schädlingsregulierung unterstützen.'],
            ['slug' => 'bande-enherbee', 'term' => 'Grasstreifen', 'definition' => 'Bewachsene Zone an Parzellenrändern, Gewässern oder Wegen zur Verringerung von Abfluss, Erosion und Stoffeinträgen.'],
            ['slug' => 'bilan-carbone', 'term' => 'CO2-Bilanz', 'definition' => 'Bewertung der Treibhausgasemissionen einer Aktivität, eines Betriebs oder einer Wertschöpfungskette.'],
            ['slug' => 'biodiversite-fonctionnelle', 'term' => 'Funktionale Biodiversität', 'definition' => 'Teil der Biodiversität, der direkte Dienste für Landwirtschaft leistet, etwa Bestäubung, biologische Regulierung oder Bodenleben.'],
            ['slug' => 'bocage', 'term' => 'Heckenlandschaft', 'definition' => 'Agrarlandschaft mit von Hecken umgebenen Parzellen, die Biodiversität und Bodenschutz fördert.'],
            ['slug' => 'cahier-des-charges', 'term' => 'Pflichtenheft', 'definition' => 'Dokument mit Regeln für Produktion, Label, Zertifizierung, Verarbeitung oder Geschäftsbeziehung.'],
            ['slug' => 'certification', 'term' => 'Zertifizierung', 'definition' => 'Kontrollverfahren, das die Einhaltung definierter Anforderungen bestätigt.'],
            ['slug' => 'chaine-du-froid', 'term' => 'Kühlkette', 'definition' => 'Temperaturbedingungen, die sensible Produkte sicher und qualitativ stabil halten.'],
            ['slug' => 'circuit-court', 'term' => 'Kurze Lieferkette', 'definition' => 'Verkaufsform mit wenigen Zwischenstufen zwischen Erzeuger und Käufer; sie garantiert nicht automatisch Nähe, fairen Preis oder geringe Umweltwirkung.'],
            ['slug' => 'compost', 'term' => 'Kompost', 'definition' => 'Stabilisierte organische Substanz aus kontrolliertem Abbau pflanzlicher oder Lebensmittelreste zur Bodenverbesserung.'],
            ['slug' => 'conditionnalite', 'term' => 'Konditionalität', 'definition' => 'Anforderungen, die Empfänger bestimmter Agrarhilfen einhalten müssen, etwa zu Umwelt, Rückverfolgbarkeit oder guter Praxis.'],
            ['slug' => 'cooperative-agricole', 'term' => 'Agrarkooperative', 'definition' => 'Gemeinschaftliche Organisation ihrer Mitglieder zur Bündelung von Verarbeitung, Lagerung, Einkauf, Verkauf oder Beratung.'],
            ['slug' => 'couvert-vegetal', 'term' => 'Bodenbedeckung', 'definition' => 'Pflanzenbestand zwischen Hauptkulturen, der den Boden schützt und bereichert.'],
            ['slug' => 'couverts-permanents', 'term' => 'Dauerhafte Bodenbedeckung', 'definition' => 'Kontinuierliche Vegetation auf dem Boden zur Erosionsminderung und Strukturverbesserung.'],
            ['slug' => 'cultures-associees', 'term' => 'Mischkulturen', 'definition' => 'Gleichzeitiger Anbau mehrerer Arten auf einer Parzelle, um Ressourcen besser zu nutzen.'],
            ['slug' => 'cultures-intermediaires', 'term' => 'Zwischenfrüchte', 'definition' => 'Kulturen zwischen zwei Hauptkulturen zur Bodenbedeckung, Nährstoffbindung oder Biomasseproduktion.'],
            ['slug' => 'densite-de-chargement', 'term' => 'Besatzdichte', 'definition' => 'Anzahl von Tieren je Fläche, wichtig für Weidedruck und Ressourcennutzung.'],
            ['slug' => 'digestat', 'term' => 'Gärrest', 'definition' => 'Reststoff aus der Methanisierung, der bei kontrollierter Zusammensetzung als organischer Dünger genutzt werden kann.'],
            ['slug' => 'diversification', 'term' => 'Diversifizierung', 'definition' => 'Ergänzung neuer Produktionen, Aktivitäten oder Verkaufswege zur Absicherung von Einkommen.'],
            ['slug' => 'economie-circulaire', 'term' => 'Kreislaufwirtschaft', 'definition' => 'Organisation, die Abfälle und unnötige Zukäufe durch bessere Nutzung von Stoffen, Nebenprodukten, Energie oder Verpackungen begrenzt.'],
            ['slug' => 'eco-regime', 'term' => 'Öko-Regelung', 'definition' => 'Jährliche GAP-Zahlung für definierte Umweltpraktiken oder Kriterien mit Bedingungen.'],
            ['slug' => 'effluents-d-elevage', 'term' => 'Wirtschaftsdünger aus Tierhaltung', 'definition' => 'Tierische Ausscheidungen und Mischungen wie Gülle, Mist oder Jauche, die unter Bedingungen als Dünger dienen.'],
            ['slug' => 'elevage-extensif', 'term' => 'Extensive Tierhaltung', 'definition' => 'Haltungssystem mit niedriger Tierdichte und starker Nutzung von Grünlandflächen.'],
            ['slug' => 'empreinte-eau', 'term' => 'Wasserfußabdruck', 'definition' => 'Indikator für direkt oder indirekt genutzte Wassermengen zur Herstellung eines Produkts oder Dienstes.'],
            ['slug' => 'erosion-des-sols', 'term' => 'Bodenerosion', 'definition' => 'Verlust von Bodenpartikeln durch Wasser oder Wind, der Bodenfruchtbarkeit verringern kann.'],
            ['slug' => 'ferme-pedagogique', 'term' => 'Lernbauernhof', 'definition' => 'Betrieb, der Besucher empfängt und Produktion, Berufe, Saisons, Ernährung und Lebendiges erklärt.'],
            ['slug' => 'fertilite-du-sol', 'term' => 'Bodenfruchtbarkeit', 'definition' => 'Fähigkeit eines Bodens, Wasser, Nährstoffe und günstige Wachstumsbedingungen bereitzustellen.'],
            ['slug' => 'filiere', 'term' => 'Wertschöpfungskette', 'definition' => 'Akteurskette von der Produktion über Verarbeitung bis zur Verteilung eines Agrarprodukts.'],
            ['slug' => 'gestion-de-l-eau-a-la-parcelle', 'term' => 'Wassermanagement auf der Parzelle', 'definition' => 'Praktiken, die Infiltration fördern, Abfluss begrenzen und verfügbares Wasser für Kulturen sichern.'],
            ['slug' => 'gestion-integree-des-ravageurs', 'term' => 'Integrierter Pflanzenschutz', 'definition' => 'Kombination aus Vorbeugung, Beobachtung und gezielten Eingriffen zur Begrenzung von Schädlingsschäden.'],
            ['slug' => 'haie-vive', 'term' => 'Lebende Hecke', 'definition' => 'Reihe aus Sträuchern und Bäumen mit Funktionen für Biodiversität, Wind, Wasser und Landschaft.'],
            ['slug' => 'humus', 'term' => 'Humus', 'definition' => 'Stabile organische Bodenfraktion, die Struktur, Fruchtbarkeit und Wasserspeicherung unterstützt.'],
            ['slug' => 'intrants', 'term' => 'Betriebsmittel', 'definition' => 'Produkte für die Produktion: Saatgut, Dünger, Pflanzenschutz, Energie, Tierfutter und weitere Inputs.'],
            ['slug' => 'irrigation-raisonnee', 'term' => 'Bedarfsgerechte Bewässerung', 'definition' => 'Wasserzufuhr, die am tatsächlichen Kulturbedarf ausgerichtet ist und Übermengen vermeidet.'],
            ['slug' => 'lutte-biologique', 'term' => 'Biologische Bekämpfung', 'definition' => 'Nutzung lebender Organismen oder natürlicher Mechanismen zur Begrenzung von Schädlingen oder Krankheiten.'],
            ['slug' => 'maec', 'term' => 'Agrarumwelt- und Klimamaßnahmen', 'definition' => 'Meist mehrjährige Verpflichtungen, die gezielte Praktiken auf Wiesen, Hecken, Böden, Wasser oder Biodiversität honorieren.'],
            ['slug' => 'matiere-organique', 'term' => 'Organische Substanz', 'definition' => 'Abbauende pflanzliche und tierische Reste, die Bodenleben und Bodenstruktur nähren.'],
            ['slug' => 'methanisation', 'term' => 'Methanisierung', 'definition' => 'Biologischer Prozess, der organische Stoffe in Biogas und verwertbare Gärreste umwandelt.'],
            ['slug' => 'natura-2000', 'term' => 'Natura 2000', 'definition' => 'Europäisches Netz von Gebieten, in denen bestimmte Lebensräume und Arten erhalten werden sollen.'],
            ['slug' => 'nitrates', 'term' => 'Nitrate', 'definition' => 'Mineralische Stickstoffformen, die Pflanzen nutzen, die aber bei Überschuss oder schlechtem Timing Wasser belasten können.'],
            ['slug' => 'pac', 'term' => 'GAP', 'definition' => 'Gemeinsame Agrarpolitik der EU, die Hilfen, Pflichten und Ausrichtungen organisiert und regional umgesetzt wird.'],
            ['slug' => 'paiement-pour-services-environnementaux', 'term' => 'Zahlung für Umweltleistungen', 'definition' => 'Mechanismus zur Vergütung messbarer Umweltleistungen wie Wasser- oder Biodiversitätsschutz.'],
            ['slug' => 'paturage-tournant', 'term' => 'Rotationsweide', 'definition' => 'Weidemanagement, das beweidete Parzellen wechselt, um Grasnachwuchs zu verbessern.'],
            ['slug' => 'pertes-post-recolte', 'term' => 'Nachernteverluste', 'definition' => 'Mengenverluste zwischen Ernte und Verbrauch durch Lagerung, Transport oder Verarbeitung.'],
            ['slug' => 'plan-de-fumure', 'term' => 'Düngeplan', 'definition' => 'Planung von Nährstoffgaben nach Kulturbedarf und Bodeneigenschaften.'],
            ['slug' => 'pollinisation', 'term' => 'Bestäubung', 'definition' => 'Übertragung von Pollen, wichtig für viele Obst-, Gemüse- und Saatgutkulturen.'],
            ['slug' => 'polyculture-elevage', 'term' => 'Ackerbau-Tierhaltungs-System', 'definition' => 'Betriebssystem, das Kulturen und Tierhaltung kombiniert, um Ressourcen besser zu verwerten.'],
            ['slug' => 'prairie-permanente', 'term' => 'Dauergrünland', 'definition' => 'Langfristig bestehende Wiese oder Weide mit Funktionen für Tierhaltung und Ökosysteme.'],
            ['slug' => 'prairie-temporaire', 'term' => 'Wechselgrünland', 'definition' => 'Für begrenzte Zeit in eine Fruchtfolge eingebundene Wiese zur Futterproduktion oder Bodenstruktur.'],
            ['slug' => 'prix-au-kilo', 'term' => 'Kilopreis', 'definition' => 'Vergleichsindikator, der Kosten auf ein Kilogramm bezieht und Formate vergleichbarer macht.'],
            ['slug' => 'prix-remunerateur', 'term' => 'Existenzsichernder Preis', 'definition' => 'Preis, der Produktionskosten deckt und ein tragfähiges Einkommen ermöglicht.'],
            ['slug' => 'proteagineux', 'term' => 'Eiweißpflanzen', 'definition' => 'Proteinreiche Kulturen wie Erbsen, Ackerbohnen oder Lupinen für menschliche oder tierische Ernährung.'],
            ['slug' => 'qualite-differenciee', 'term' => 'Differenzierte Qualität', 'definition' => 'Aufwertung eines Produkts durch überprüfbare Merkmale zu Qualität, Produktionsweise oder Herkunft.'],
            ['slug' => 'relocalisation-alimentaire', 'term' => 'Ernährungslokalisierung', 'definition' => 'Stärkung von Produktion, Verarbeitung, Verteilung und Konsum auf näherer territorialer Ebene.'],
            ['slug' => 'reserve-utile-du-sol', 'term' => 'Nutzbare Feldkapazität', 'definition' => 'Wassermenge, die ein Boden speichern und Pflanzen zur Verfügung stellen kann.'],
            ['slug' => 'resilience', 'term' => 'Resilienz', 'definition' => 'Fähigkeit eines Betriebs, Klima-, Preis- oder Gesundheitskrisen abzufedern und weiter zu funktionieren.'],
            ['slug' => 'restauration-collective', 'term' => 'Gemeinschaftsverpflegung', 'definition' => 'Mahlzeiten in Schulen, Krankenhäusern, Pflegeheimen, Unternehmen oder Verwaltungen mit Potenzial für lokale Absatzwege.'],
            ['slug' => 'rotation', 'term' => 'Fruchtfolge', 'definition' => 'Geplante Abfolge von Kulturen auf derselben Parzelle.'],
            ['slug' => 'saisonnalite', 'term' => 'Saisonalität', 'definition' => 'Natürliche Produktionszeit eines Lebensmittels, die Verfügbarkeit, Geschmack, Kosten und Wirkung beeinflusst.'],
            ['slug' => 'semis-direct', 'term' => 'Direktsaat', 'definition' => 'Aussaat ohne vorheriges Pflügen zur Verringerung der Bodenbearbeitung und zum Schutz der Struktur.'],
            ['slug' => 'sequestration-carbone', 'term' => 'Kohlenstoffbindung', 'definition' => 'Speicherung von Kohlenstoff in Böden und Biomasse als Beitrag zur Klimaminderung.'],
            ['slug' => 'services-ecosystemiques', 'term' => 'Ökosystemleistungen', 'definition' => 'Nutzen von Ökosystemen für Menschen, etwa Bestäubung, Wasserfilterung, Kohlenstoffspeicherung oder Bodenfruchtbarkeit.'],
            ['slug' => 'souverainete-alimentaire', 'term' => 'Ernährungssouveränität', 'definition' => 'Politische und wirtschaftliche Fähigkeit, Produktion, Verarbeitung, Verteilung und Ernährungssicherheit eines Gebiets zu gestalten.'],
            ['slug' => 'stress-hydrique', 'term' => 'Wasserstress', 'definition' => 'Situation, in der der Wasserbedarf von Kulturen die Verfügbarkeit übersteigt.'],
            ['slug' => 'systeme-alimentaire-territorial', 'term' => 'Territoriales Ernährungssystem', 'definition' => 'Lokale Organisation von Produktion, Verarbeitung, Verteilung, Konsum, Abfall, öffentlicher Hand und Bürgerschaft rund um Ernährung.'],
            ['slug' => 'techniques-culturales-simplifiees', 'term' => 'Vereinfachte Bodenbearbeitung', 'definition' => 'Praktiken mit weniger intensiver Bodenbearbeitung als Pflügen, um Erosion, Strukturverluste und Kosten zu begrenzen.'],
            ['slug' => 'tracabilite', 'term' => 'Rückverfolgbarkeit', 'definition' => 'Möglichkeit, ein Produkt von seiner Herkunft bis zum Verkauf anhand überprüfbarer Informationen zu verfolgen.'],
            ['slug' => 'transformation-a-la-ferme', 'term' => 'Verarbeitung am Hof', 'definition' => 'Verwertung eigener Produkte direkt auf dem Betrieb, zum Beispiel Käse, Saft oder Joghurt.'],
            ['slug' => 'transition-agroecologique', 'term' => 'Agroökologischer Wandel', 'definition' => 'Veränderungsweg mit technischen Versuchen, wirtschaftlicher Tragfähigkeit, Arbeitsbedingungen und messbaren Wirkungen auf Lebendiges.'],
            ['slug' => 'valeur-ajoutee', 'term' => 'Wertschöpfung', 'definition' => 'Geschaffener Wert durch Verarbeitung, Qualität, Herkunft oder Vermarktungsform.'],
            ['slug' => 'vente-directe', 'term' => 'Direktverkauf', 'definition' => 'Verkauf vom Erzeuger an den Konsumenten ohne kommerziellen Zwischenhändler, am Hof, Markt, Abholpunkt oder online.'],
            ['slug' => 'amendement-organique', 'term' => 'Organische Bodenverbesserung', 'definition' => 'Gabe von Kompost, Mist oder Gärrest zur Verbesserung von Bodenstruktur, Bodenleben und Wasserspeicherung.'],
            ['slug' => 'analyse-de-sol', 'term' => 'Bodenanalyse', 'definition' => 'Untersuchung einer Bodenprobe auf pH, organische Substanz, Nährstoffe und Anpassungsbedarf.'],
            ['slug' => 'apiculture', 'term' => 'Imkerei', 'definition' => 'Haltung von Bienen zur Honigproduktion und als Beitrag zur Bestäubung und Landschaftsbeobachtung.'],
            ['slug' => 'battance', 'term' => 'Verschlämmung', 'definition' => 'Krustenbildung an der Bodenoberfläche nach Regen, die Infiltration und Auflaufen der Saat erschweren kann.'],
            ['slug' => 'bassin-versant', 'term' => 'Einzugsgebiet', 'definition' => 'Gebiet, dessen Niederschlagswasser zu demselben Gewässer oder Auslass abfließt.'],
            ['slug' => 'bien-etre-animal', 'term' => 'Tierwohl', 'definition' => 'Zustand eines Tieres in Bezug auf Gesundheit, Futter, Haltung, Verhalten, vermeidbares Leiden und Pflege.'],
            ['slug' => 'biomasse', 'term' => 'Biomasse', 'definition' => 'Lebende oder ehemals lebende Materie wie Erntereste, Holz, Wirtschaftsdünger oder Nebenprodukte.'],
            ['slug' => 'capteur-agricole', 'term' => 'Agrarsensor', 'definition' => 'Gerät, das Felddaten wie Feuchte, Temperatur, Bewegung, Milchleistung oder Gerätezustand misst.'],
            ['slug' => 'charge-de-travail', 'term' => 'Arbeitsbelastung', 'definition' => 'Umfang und Intensität der Arbeit auf einem Hof, geprägt durch Saison, Produktion, Arbeitskräfte und Organisation.'],
            ['slug' => 'conservation-des-aliments', 'term' => 'Lebensmittelkonservierung', 'definition' => 'Methoden zur Erhaltung von Qualität und Sicherheit: Kälte, Trocknung, Fermentation, Verarbeitung, Verpackung und Datumsmanagement.'],
            ['slug' => 'consentement-des-donnees', 'term' => 'Datenzustimmung', 'definition' => 'Einverständnis zur Nutzung oder Weitergabe bestimmter Agrardaten mit verständlichem Zweck, Empfänger und Bedingungen.'],
            ['slug' => 'culture-derobee', 'term' => 'Zweitfrucht', 'definition' => 'Kultur zwischen zwei Hauptkulturen, oft für Futter, Bodenbedeckung oder kurze Wachstumsfenster.'],
            ['slug' => 'culture-fourragere', 'term' => 'Futterkultur', 'definition' => 'Kultur zur Fütterung von Tieren, etwa Gras, Luzerne, Silomais oder Mischungen.'],
            ['slug' => 'decarbonation-agricole', 'term' => 'Dekarbonisierung der Landwirtschaft', 'definition' => 'Schrittweise Senkung der Nettoemissionen eines Betriebs durch Energieeinsparung, weniger fossile Abhängigkeit, Kohlenstoffspeicherung oder Praxisänderung.'],
            ['slug' => 'drainage-agricole', 'term' => 'Landwirtschaftliche Drainage', 'definition' => 'Anlage zur Ableitung von Wasserüberschuss aus feuchten Böden mit Wirkungen auf Tragfähigkeit, Ertrag, Biodiversität und Hydrologie.'],
            ['slug' => 'energie-renouvelable-agricole', 'term' => 'Erneuerbare Energie am Hof', 'definition' => 'Energieerzeugung auf oder mit dem Hof, etwa Solar, Biomethan, Holzenergie oder Wärmenutzung.'],
            ['slug' => 'ensilage', 'term' => 'Silage', 'definition' => 'Konservierung feuchten Futters unter Luftabschluss zur Fütterung außerhalb der Weidezeit.'],
            ['slug' => 'exploitation-familiale', 'term' => 'Familienbetrieb', 'definition' => 'Betrieb, in dem die Familie zentrale Rolle bei Arbeit, Entscheidungen und Übergabe spielt.'],
            ['slug' => 'fauche', 'term' => 'Mahd', 'definition' => 'Schnitt von Wiesen oder Futterkulturen für Heu, Silage oder Ballensilage.'],
            ['slug' => 'foncier-agricole', 'term' => 'Landwirtschaftliche Fläche', 'definition' => 'Flächen für Produktion, Gründung oder Übergabe landwirtschaftlicher Aktivitäten mit Preis-, Pacht- und Nutzungsfragen.'],
            ['slug' => 'fourrage', 'term' => 'Futter', 'definition' => 'Pflanzliche Nahrung für Nutztiere, frisch, beweidet, getrocknet, siliert oder als Ballensilage.'],
            ['slug' => 'groupe-d-achat', 'term' => 'Einkaufsgemeinschaft', 'definition' => 'Gruppe von Konsumenten, die Bestellungen bei Produzenten oder Lieferanten bündelt.'],
            ['slug' => 'interculture', 'term' => 'Zwischenkulturzeit', 'definition' => 'Zeit zwischen zwei Hauptkulturen, in der der Boden nackt bleiben, bedeckt werden oder eine Zwischenfrucht tragen kann.'],
            ['slug' => 'interoperabilite', 'term' => 'Interoperabilität', 'definition' => 'Fähigkeit digitaler Werkzeuge, verständliche Daten ohne unnötige Neueingabe auszutauschen.'],
            ['slug' => 'labour', 'term' => 'Pflügen', 'definition' => 'Bodenbearbeitung, die Erde vor einer Kultur wendet und je nach Kontext mit Erosion, Struktur, Energie und Bodenleben abzuwägen ist.'],
            ['slug' => 'logistique-alimentaire', 'term' => 'Lebensmittellogistik', 'definition' => 'Organisation von Transport, Lagerung, Verpackung und Lieferung, damit Produkte rechtzeitig und in gutem Zustand ankommen.'],
            ['slug' => 'marche-public-alimentaire', 'term' => 'Öffentliche Lebensmittelbeschaffung', 'definition' => 'Beschaffungsverfahren öffentlicher Einrichtungen für Mahlzeiten oder Lebensmittel mit Kriterien zu Qualität, Herkunft, Saison oder Logistik.'],
            ['slug' => 'mycorhizes', 'term' => 'Mykorrhiza', 'definition' => 'Verbindungen zwischen Bodenpilzen und Pflanzenwurzeln, die Nährstoffzugang und Bodenleben unterstützen können.'],
            ['slug' => 'outil-d-aide-a-la-decision', 'term' => 'Entscheidungshilfe', 'definition' => 'Digitales, technisches oder methodisches Werkzeug, das Eingriffe anhand von Daten, Regeln, Beobachtungen und Zielen unterstützt.'],
            ['slug' => 'ph-du-sol', 'term' => 'Boden-pH', 'definition' => 'Säure- oder Alkalitätsindikator des Bodens, wichtig für Nährstoffverfügbarkeit und Bodenleben.'],
            ['slug' => 'point-relais', 'term' => 'Abholpunkt', 'definition' => 'Ort, an dem bestellte oder gebündelte Produkte an Konsumenten übergeben werden.'],
            ['slug' => 'prix-de-revient', 'term' => 'Selbstkostenpreis', 'definition' => 'Vollständige Kosten zur Herstellung eines Produkts oder Dienstes einschließlich Arbeit, Abschreibung und Verluste.'],
            ['slug' => 'projet-alimentaire-territorial', 'term' => 'Territoriales Ernährungsprojekt', 'definition' => 'Gemeinsamer Ansatz, der Ernährung eines Gebiets über Produktion, Verarbeitung, Verteilung, Gastronomie, Gesundheit und Politik organisiert.'],
            ['slug' => 'ruissellement', 'term' => 'Oberflächenabfluss', 'definition' => 'Wasserfluss an der Oberfläche, wenn Regen nicht schnell genug versickert und Boden oder Nährstoffe mitnehmen kann.'],
            ['slug' => 'sante-animale', 'term' => 'Tiergesundheit', 'definition' => 'Gesundheitsüberwachung von Herden oder Tieren mit Prävention, Beobachtung, Pflege und Biosicherheit.'],
            ['slug' => 'stockage-a-la-ferme', 'term' => 'Lagerung am Hof', 'definition' => 'Fähigkeit, Ernten, Futter, Betriebsmittel oder verarbeitete Produkte am Betrieb aufzubewahren.'],
            ['slug' => 'tableau-de-bord-agricole', 'term' => 'Agrar-Dashboard', 'definition' => 'Zusammenfassung betrieblicher oder sektorbezogener Indikatoren, nützlich bei zuverlässigen und entscheidungsrelevanten Daten.'],
            ['slug' => 'tassement-du-sol', 'term' => 'Bodenverdichtung', 'definition' => 'Verdichtung durch Befahrung, Gewicht oder nasse Bedingungen, die Poren, Wurzeln, Infiltration und Bearbeitung beeinträchtigt.'],
            ['slug' => 'travail-du-sol', 'term' => 'Bodenbearbeitung', 'definition' => 'Mechanische Eingriffe in den Boden vom Pflügen bis zur Direktsaat, gewählt nach Ziel, Boden, Wetter, Kultur und Erosionsrisiko.'],
            ['slug' => 'unite-gros-betail-ugb', 'term' => 'Großvieheinheit', 'definition' => 'Vergleichsgröße, die unterschiedliche Nutztiere in eine gemeinsame Einheit für Besatz, Flächen oder Futterbedarf überführt.'],
            ['slug' => 'variete-resistante', 'term' => 'Resistente Sorte', 'definition' => 'Sorte, die Krankheit, Stress oder Bedingungen besser widersteht, ohne Beobachtung überflüssig zu machen.'],
            ['slug' => 'verger-haute-tige', 'term' => 'Hochstammobstwiese', 'definition' => 'Obstwiese mit hochstämmigen Bäumen, oft verbunden mit Grünland, traditioneller Landschaft und Biodiversität.'],
            ['slug' => 'zone-humide', 'term' => 'Feuchtgebiet', 'definition' => 'Gebiet, in dem Wasser Boden, Vegetation und Nutzung dauerhaft prägt.'],
            ['slug' => 'wallesmart', 'term' => 'WALLeSmart', 'definition' => 'Wallonische digitale Plattform, die den sicheren Austausch landwirtschaftlicher Daten zwischen Werkzeugen, Betrieben und autorisierten Partnern erleichtert.'],
            ['slug' => 'zero-artificialisation-nette-zan', 'term' => 'Netto-Null-Flächenversiegelung (ZAN)', 'definition' => 'Ziel sparsamer Bodennutzung: neue versiegelte oder bebaute Flächen verringern und Verluste ausgleichen, wenn Regeln es vorsehen.'],
            ['slug' => 'zone-tampon', 'term' => 'Pufferzone', 'definition' => 'Bereich zwischen landwirtschaftlicher Aktivität und empfindlichem Milieu zur Verringerung von Einträgen und zum Schutz von Wasser oder Biodiversität.'],
        ],
        'dossiers' => [
            [
                'id' => 'eau-sols-secheresse',
                'title' => 'Wasser, Böden und Trockenheit',
                'subtitle' => 'Verstehen, wie landwirtschaftliche Böden Wasser speichern, Abfluss begrenzen und Kulturen bei Trockenheit schützen.',
                'audience' => 'Bürgerinnen und Bürger, Familien, Lehrkräfte, Gemeinden, lokale Vereine und Einkaufsgemeinschaften.',
                'duration' => 'Geführte Lektüre: 25 bis 35 Minuten',
                'illustration' => '/assets/img/dossier-eau-sols.png',
                'illustration_alt' => 'Pädagogische Grafik zu bedecktem Boden, Wasserspeicher und Infiltration auf einer Agrarparzelle.',
                'learning_objectives' => [
                    'Erklären, warum landwirtschaftliche Trockenheit von Regen, Boden, Kulturen und Praktiken abhängt.',
                    'Faktoren erkennen, die Oberflächenabfluss verschärfen oder reduzieren.',
                    'Düngung, Nitrate, Bodenbedeckung und Wasserschutz verbinden.',
                    'Eine überprüfbare Frage an Betrieb, Gemeinde oder Einzugsgebietsmanagement formulieren.',
                ],
                'pedagogical_use' => [
                    'Mit dem Kapitel beginnen, das zum lokalen Problem passt: Trockenheit, Schlammabfluss oder Wasserqualität.',
                    'Erst die Zusammenfassung lesen, dann die angeleitete Aktivität als Gesprächsgrundlage nutzen.',
                    'Mit Diskussionsfragen und Glossar prüfen, ob die Schlüsselbegriffe verstanden wurden.',
                    'Referenzen für Hofbesuch, Bürgertreffen oder Unterrichtssequenz aufbewahren.',
                ],
                'activity_kit' => [
                    'Lokale Karte oder Luftbild mit Wegen, Gräben, Gewässern und Parzellen.',
                    'Zwei durchlöcherte Flaschen, nackte Erde, bedeckte Erde oder Kompost, Messbecher und Stoppuhr.',
                    'Notizblätter für Beobachtung, Hypothese, Nachweis und Frage.',
                    'Fotos von bedeckten Feldern, nackten Böden, Hecken, Starkregen und Schlammabfluss.',
                ],
                'evaluation' => [
                    'Unterschied zwischen gefallenem Regen, infiltriertem Wasser und für Kulturen verfügbarem Wasser erklären lassen.',
                    'Drei Praktiken nach ihrer Hauptwirkung sortieren: bedecken, infiltrieren, verlangsamen oder düngen.',
                    'Eine Mindmap zu Boden, Wasser, Hang, Vegetation, Stickstoff und Handlungsmöglichkeiten erstellen.',
                    'Mit einer überprüfbaren Frage an eine zuständige Quelle abschließen.',
                ],
                'vocabulary' => ['Grasstreifen', 'Bodenbedeckung', 'Bodenerosion', 'Organische Substanz', 'Nitrate', 'Nutzbare Feldkapazität', 'Oberflächenabfluss', 'Wasserstress', 'Pufferzone'],
                'chapters' => [
                    [
                        'id' => 'reserve-eau-sol',
                        'title' => 'Der Boden als Wasserspeicher',
                        'summary' => 'Ein lebendiger Boden wirkt wie ein Speicher: Struktur, organische Substanz und Bedeckung bestimmen einen Teil des für Kulturen verfügbaren Wassers.',
                        'paragraphs' => [
                            'Bei landwirtschaftlicher Trockenheit zählt nicht nur die gefallene Regenmenge. Entscheidend ist auch, was der Boden speichern und an Pflanzen zurückgeben kann.',
                            'Zwischenfrüchte, längere Fruchtfolgen, organische Substanz, weniger Verdichtung und angepasste Sorten können die Wasserhaltefähigkeit verbessern.',
                            'Für Bürgerinnen und Bürger erklärt dies, warum zwei Nachbarfelder auf dieselbe Trockenperiode unterschiedlich reagieren können.',
                        ],
                        'key_points' => ['Die nutzbare Feldkapazität hängt von Textur, Tiefe, Struktur und organischer Substanz ab.', 'Bedeckter Boden begrenzt Verdunstung und schützt die Oberfläche.', 'Trockenheitsanpassung verbindet Agronomie, Sortenwahl, Arbeitskalender und Wassermanagement.'],
                        'citizen_actions' => ['Beobachten, ob Felder im Winter oder zwischen Kulturen bedeckt bleiben.', 'Bei Hofbesuchen nach dem Umgang mit Trockenheit fragen.', 'Saisonale Produkte bevorzugen, die besser zu lokalen Produktionszyklen passen.'],
                        'pedagogical_sequence' => ['Zwei Fotos von Parzellen nach Trockenheit vergleichen.', 'Vier Faktoren erklären: Textur, Tiefe, Struktur und organische Substanz.', 'Jede Praxis mit einer erwarteten Wirkung verbinden.', 'Zwischen Wetter, Parzelle, Betrieb und Gebiet unterscheiden.'],
                        'workshop' => [
                            'title' => 'Den Schwammeffekt eines bedeckten Bodens testen',
                            'duration' => '35 bis 45 Minuten',
                            'objective' => 'Infiltrationsgeschwindigkeit und Wassertrübung zwischen nacktem und bedecktem Boden vergleichen.',
                            'steps' => ['Zwei geneigte Behälter vorbereiten: einer mit nackter Erde, einer mit Pflanzenresten oder Kompost.', 'Gleiche Wassermenge im gleichen Tempo auf beide Proben gießen.', 'Wassermenge, Farbe, Abflussgeschwindigkeit und mitgerissene Partikel beobachten.', 'Die Beobachtung mit Feldpraktiken verbinden, ohne zu verallgemeinern.'],
                            'debrief' => 'Der Test ersetzt keine Bodenanalyse, macht aber die Rolle von Bedeckung und Struktur sichtbar.',
                        ],
                        'discussion_questions' => ['Warum reagieren Nachbarfelder nicht gleich auf Trockenheit?', 'Welche Praktiken verbessern Wasserspeicherung ohne neue Abhängigkeit von Bewässerung?', 'Welche Informationen braucht man, bevor man ein Wassermanagement beurteilt?'],
                        'teacher_notes' => ['Betonen, dass Boden ein physikalisches, chemisches und biologisches Milieu ist.', 'Den Schwammeffekt nicht übertreiben: lange Trockenheit bleibt ein Risiko.', 'Beobachtung, Hypothese und Nachweis klar trennen.'],
                    ],
                    [
                        'id' => 'erosion-ruissellement',
                        'title' => 'Erosion und Oberflächenabfluss',
                        'summary' => 'Starkregen kann fruchtbare Erde mitreißen, Schlammströme auslösen und Partikel in Gräben, Straßen und Gewässer transportieren.',
                        'paragraphs' => ['Wassererosion entsteht, wenn Regentropfen Bodenpartikel lösen und Wasser abfließt statt zu versickern.', 'Schutzmaßnahmen bedecken den Boden, verlangsamen Wasser, erhöhen Infiltration und verkürzen Hanglängen.', 'Das Thema betrifft auch Anwohner, weil Schlamm Straßen, Keller, Gewässer und Lebensqualität beeinflusst.'],
                        'key_points' => ['Verlorener Boden braucht lange, um sich neu zu bilden.', 'Vorbeugung ist wirksamer als Reparatur nach einem Ereignis.', 'Sensibilitätskarten helfen, besonders gefährdete Parzellen zu erkennen.'],
                        'citizen_actions' => ['Wiederkehrende Abflusszonen bei der Gemeinde oder zuständigen Akteuren melden.', 'Hecken, Grasstreifen und Maßnahmen unterstützen, die Wasser verlangsamen.', 'Eine Parzelle nicht anhand eines Einzelbildes bewerten.'],
                        'pedagogical_sequence' => ['Mit einem lokalen Beispiel beginnen.', 'Risikofaktoren identifizieren: Hang, nackter Boden, Regenintensität, Verdichtung.', 'Lösungen danach vergleichen, ob sie bedecken, bremsen oder Wege verkürzen.', 'Von Schuldzuweisung zu Einzugsgebiet und Prävention wechseln.'],
                        'workshop' => [
                            'title' => 'Einen Abflussweg kartieren',
                            'duration' => '45 Minuten',
                            'objective' => 'Relief lesen und erkennen, wo Wasser beschleunigt, Erde transportiert oder gebremst werden kann.',
                            'steps' => ['Ein bekanntes Viertel oder Tal wählen.', 'Den wahrscheinlichen Wasserweg bei Starkregen einzeichnen.', 'Mögliche Lösungen platzieren: Grasstreifen, Hecke, Grabenpflege oder Bodenbedeckung.', 'Lösungen nach Ebene sortieren: Parzelle, Betrieb, Straße, Gemeinde, Einzugsgebiet.'],
                            'debrief' => 'Erosionsprävention kombiniert landwirtschaftliche Praktiken, Landschaftselemente und lokale Koordination.',
                        ],
                        'discussion_questions' => ['Warum ist Schlamm auf der Straße auch ein Thema der Bodenfruchtbarkeit?', 'Welche Lösungen liegen beim Betrieb, welche bei der Gemeinde?', 'Wie diskutiert man Erosion ohne Anwohner und Betriebe gegeneinanderzustellen?'],
                        'teacher_notes' => ['Zeigen, dass Hang allein nicht genügt: Boden, Kultur und Gewitter zählen ebenfalls.', 'Sichtbare Landschaftselemente als konkrete Beispiele nutzen.', 'Erosion mit Wasserqualität und gemeinsamen Reinigungskosten verbinden.'],
                    ],
                    [
                        'id' => 'eau-nitrates',
                        'title' => 'Nitrate und Wasserqualität',
                        'summary' => 'Stickstoff ist für Pflanzen notwendig, doch Überschüsse oder falsche Zeitpunkte können Nitratverluste ins Wasser begünstigen.',
                        'paragraphs' => ['Nitrate sind mineralische Stickstoffformen. Kulturen brauchen sie, doch sie können mit Wasser wandern, wenn Pflanzen sie nicht aufnehmen.', 'Düngepläne, Zwischenfrüchte, Sperrzeiten, Bodenanalysen und Beratung sollen Bedarf und Düngung besser synchronisieren.', 'Das Ziel ist nicht, Stickstoff zu verbannen, sondern ihn am richtigen Ort, zur richtigen Zeit und in passender Menge einzusetzen.'],
                        'key_points' => ['Düngung muss am tatsächlichen Bedarf der Kulturen ausgerichtet sein.', 'Verluste steigen, wenn Stickstoff ohne aktive Kultur verfügbar bleibt.', 'Wasserqualität braucht Regeln, Praktiken und langfristige Kontrolle.'],
                        'citizen_actions' => ['Nützliche Düngung und Überdüngung unterscheiden.', 'An lokalen Animationen zu Wasser, Böden und Landschaft teilnehmen.', 'Sensible Informationen vor dem Teilen bei zuständigen Stellen prüfen.'],
                        'pedagogical_sequence' => ['Stickstoff zuerst als notwendigen Nährstoff vorstellen.', 'Einen einfachen Zyklus verfolgen: Gabe, Aufnahme, Rest, Regen, möglicher Transfer.', 'Drei Situationen vergleichen: nackter Boden, aktive Kultur, Zwischenfrucht.', 'Regeln mit Trinkwasser, Gesundheit und Verantwortung verbinden.'],
                        'workshop' => [
                            'title' => 'Den Nitrat-Risikokalender bauen',
                            'duration' => '40 Minuten',
                            'objective' => 'Verstehen, warum Zeitpunkt der Gabe und aktive Pflanzen den Verlust verändern.',
                            'steps' => ['Eine Jahresleiste mit Ernte, Herbstregen, Kälte, Aussaat und Wachstum zeichnen.', 'Karten wie Düngung, aktive Kultur, nackter Boden, Regen und Zwischenfrucht platzieren.', 'Zeiten erkennen, in denen Stickstoff ohne Pflanzenaufnahme verfügbar bleibt.', 'Eine verständliche Vorsichtsregel formulieren.'],
                            'debrief' => 'Wasserqualität hängt ebenso vom Kalender und der Kontrolle ab wie von der Gesamtmenge des Stickstoffs.',
                        ],
                        'discussion_questions' => ['Warum ist das Ziel nicht, Stickstoff in der Landwirtschaft abzuschaffen?', 'Welche Informationen machen Kritik an Düngung fairer?', 'Wie verbindet man Trinkwasser, Landwirtschaft und Ernährung ohne Vereinfachung?'],
                        'teacher_notes' => ['Nicht nur mineralische Dünger betrachten: Wirtschaftsdünger und Bodenmineralisierung zählen auch.', 'Wasserüberwachung erfolgt langfristig, nicht anhand eines Einzelereignisses.', 'Dosis, Zeitpunkt, Kulturbedarf und Transferrisiko unterscheiden.'],
                    ],
                ],
                'references' => [
                    ['label' => 'SPW Landwirtschaft - Wassermanagement', 'url' => 'https://agriculture.wallonie.be/home/recherche-developpement/adaptations-a-la-secheresse/resilience-en-grandes-cultures/efficience-en-eau.html'],
                    ['label' => 'SPW Landwirtschaft - Schutz landwirtschaftlicher Böden', 'url' => 'https://agriculture.wallonie.be/home/ruralite-et-foncier/ruralite/protection-des-sols/prevention-et-lutte-contre-l-erosion-des-sols/mesures-de-protection-de-sols-agricoles.html'],
                    ['label' => 'SPW Umwelt - Nitrate und Trinkwasser', 'url' => 'https://environnement.wallonie.be/home/milieux/eau/etat-des-eaux/eau-de-distribution/qualite-de-l-eau-de-distribution/nitrates.html'],
                ],
            ],
            [
                'id' => 'circuits-courts-alimentation-locale',
                'title' => 'Kurze Lieferketten und lokale Ernährung',
                'subtitle' => 'Lokale Herkunft, Direktverkauf, lokale Verarbeitung, fairen Preis und Saisonkonsum unterscheiden lernen.',
                'audience' => 'Haushalte, Schulen, Verbrauchervereine, Gemeinden, Kantinen und Bürgerinitiativen.',
                'duration' => 'Geführte Lektüre: 20 bis 30 Minuten',
                'illustration' => '/assets/img/dossier-circuits-courts.png',
                'illustration_alt' => 'Pädagogische Grafik zu einem lokalen Verkaufspunkt zwischen Produzenten, Produkten und Konsumenten.',
                'learning_objectives' => [
                    'Lokales Produkt, kurze Lieferkette, Direktverkauf, Saisonprodukt und lokale Verarbeitung unterscheiden.',
                    'Bestandteile eines Lebensmittelpreises verstehen.',
                    'Realistische Hebel für mehr lokale Produkte im Haushalt oder in Gemeinschaften erkennen.',
                    'Ein konstruktives Gespräch zwischen Konsumenten, Produzenten, Kantinen und Gemeinden vorbereiten.',
                ],
                'pedagogical_use' => [
                    'Einkaufsgewohnheiten erfassen, bevor Lösungen vorgeschlagen werden.',
                    'Konkrete Produktbeispiele vergleichen statt nur Grundsatzdebatten führen.',
                    'Unsichtbare logistische Zwänge sichtbar machen.',
                    'Mit einem einfachen Aktionsplan abschließen: ein Produkt, ein Ort, eine Häufigkeit, ein Prüfkriterium.',
                ],
                'activity_kit' => [
                    'Anonymisierte Kassenbons, Verpackungen, Etiketten oder Produktkarten.',
                    'Gebietskarte mit Höfen, Märkten, Geschäften, Kantinen, Verarbeitern und Abholpunkten.',
                    'Vergleichstabelle zu Herkunft, Saison, Zwischenstufen, Kilopreis und Nutzung.',
                    'Beispiel für Wochenmenü oder Kantinenmenü.',
                ],
                'evaluation' => [
                    'Fünf Produkte nach lokal, saisonal, kurz und verarbeitet sortieren lassen.',
                    'Kilopreis berechnen und besprechen, was er nicht sagt.',
                    'Eine präzise Frage an Verkäufer oder Kantine zur Herkunft formulieren lassen.',
                    'Machbarkeit eines Engagements bewerten: Kosten, Zeit, Verfügbarkeit, Lagerung und Regelmäßigkeit.',
                ],
                'vocabulary' => ['Kurze Lieferkette', 'Kilopreis', 'Existenzsichernder Preis', 'Ernährungslokalisierung', 'Gemeinschaftsverpflegung', 'Saisonalität', 'Territoriales Ernährungssystem', 'Verarbeitung am Hof', 'Direktverkauf'],
                'chapters' => [
                    [
                        'id' => 'local-circuit-court-saison',
                        'title' => 'Lokal, kurze Lieferkette und Saison: drei verschiedene Begriffe',
                        'summary' => 'Ein Produkt kann lokal sein, ohne kurz verkauft zu werden, lokal verkauft werden, ohne lokal erzeugt zu sein, oder saisonal sein, ohne aus der Nähe zu kommen.',
                        'paragraphs' => ['Lokal beschreibt geografische Nähe, sagt aber nicht alles. Wichtig sind Rohstoffherkunft, Verarbeitungsort, Zahl der Zwischenstufen und natürliche Saison.', 'Eine kurze Lieferkette betont wenige Zwischenstufen und die Beziehung zwischen Produzent und Konsument.', 'Saisonalität hilft, Geschmack, Verfügbarkeit, Budget und Wirkung zusammenzudenken.'],
                        'key_points' => ['Lokal, kurz und saisonal sind keine Synonyme.', 'Der Verarbeitungsort ist ebenso wichtig wie der Erzeugungsort.', 'Eine gute Entscheidung kombiniert Herkunft, Saison, Kilopreis, Nutzung und vermiedene Verschwendung.'],
                        'citizen_actions' => ['Nach Erzeugungs- und Verarbeitungsort fragen.', 'Ähnliche Produkte über den Kilopreis vergleichen.', 'Eine kurze Liste regelmäßig nutzbarer lokaler Produkte aufbauen.'],
                        'pedagogical_sequence' => ['Vier Lebensmittel vorstellen und sortieren lassen.', 'Eine Lesetabelle zu Herkunft, Verarbeitung, Zwischenstufen und Saison aufbauen.', 'Einen mehrdeutigen Fall analysieren.', 'Eine wiederverwendbare Arbeitsdefinition formulieren.'],
                        'workshop' => [
                            'title' => 'Den realen Weg eines Produkts lesen',
                            'duration' => '35 Minuten',
                            'objective' => 'Von einem lokalen Eindruck zu einem überprüfbaren Produktweg wechseln.',
                            'steps' => ['Ein einfaches Produkt wählen.', 'Herkunft, Verarbeiter, Verkäufer, Saison, Label und Kilopreis notieren.', 'Fehlende Informationen und Fragen erkennen.', 'Entscheiden, ob das Produkt zum Bedarf passt.'],
                            'debrief' => 'Ein informierter Einkauf sucht kein perfektes Produkt, sondern eine bewusste Entscheidung mit klaren Kriterien.',
                        ],
                        'discussion_questions' => ['Ist ein lokales Produkt immer nachhaltiger?', 'Warum zählt lokale Verarbeitung?', 'Welche Kriterien bleiben wichtig, wenn Zeit oder Budget begrenzt sind?'],
                        'teacher_notes' => ['Nachweis und Marketingwortschatz unterscheiden.', 'Haushalte nicht moralisieren, sondern wiederholbare Kompromisse suchen.', 'Erklären, dass kurze Lieferkette je nach Definition eine Zwischenstufe enthalten kann.'],
                    ],
                    [
                        'id' => 'prix-juste-budget',
                        'title' => 'Fairer Preis und Familienbudget',
                        'summary' => 'Der bezahlte Preis muss aus Sicht von Haushalt und Betrieb gelesen werden: Kosten, Saison, Mengen, Verarbeitung, Lagerung und vermiedene Verluste.',
                        'paragraphs' => ['Ein fairer Preis ist nicht nur ein niedriger Preis. Er muss Kosten decken, Arbeit vergüten und Investitionen ermöglichen.', 'Mahlzeitenplanung, Grundprodukte, weniger Verschwendung, Kilopreise und Gruppeneinkauf können Budget und lokale Beziehung verbinden.', 'Kurze Lieferketten sind nicht automatisch teurer oder günstiger. Es hängt von Produkt, Saison, Verarbeitung, Volumen und Transport ab.'],
                        'key_points' => ['Preisvergleich muss Qualität, Nutzung, Verluste und Vergütung einbeziehen.', 'Der Kilopreis begrenzt Verpackungseffekte.', 'Regelmäßige kleine lokale Einkäufe sind oft tragfähiger als seltene perfekte Einkäufe.'],
                        'citizen_actions' => ['Einen lokalen Grundkorb definieren.', 'Einen Teil der Grundprodukte selbst kochen.', 'Gute Adressen mit überprüfbaren Kriterien teilen.'],
                        'pedagogical_sequence' => ['Auflisten, was ein Lebensmittelpreis bezahlt.', 'Zwei Wochenkörbe statt zwei Einzelprodukte vergleichen.', 'Kilopreis und Kosten pro Mahlzeit einführen.', 'Einen realistischen Kompromiss bauen.'],
                        'workshop' => [
                            'title' => 'Einen realistischen lokalen Einkaufskorb bauen',
                            'duration' => '45 Minuten',
                            'objective' => 'Ein Einkaufsmodell finden, das zu Budget, Kochzeit und Angebot passt.',
                            'steps' => ['Ein Wochenbudget und drei Zwänge festlegen.', 'Fünf Basisprodukte wählen.', 'Kilopreis, Portionen, mögliche Verluste und Nährwert vergleichen.', 'Zwei Änderungen für einen Monat auswählen.'],
                            'debrief' => 'Regelmäßigkeit und weniger Verschwendung wirken oft stärker als ein teurer Einmaleinkauf.',
                        ],
                        'discussion_questions' => ['Was ist fair für Betrieb und Haushalt?', 'Welche lokalen Einkäufe sind das ganze Jahr einfach?', 'Wie spricht man über Preis, ohne Kaufkraft und Betriebseinkommen gegeneinanderzustellen?'],
                        'teacher_notes' => ['Kurze Lieferketten nicht pauschal als billig oder teuer darstellen.', 'Mit Mahlzeiten statt nur Produkten arbeiten.', 'Vermiedene Kosten wie Verschwendung und Verpackung einbeziehen.'],
                    ],
                    [
                        'id' => 'collectif-cantines-communes',
                        'title' => 'Schulen, Kantinen und Gemeinden: gemeinsam handeln',
                        'summary' => 'Gemeinschaften können lokale Sektoren durch Einkauf, Pädagogik und regelmäßige Absatzwege unterstützen.',
                        'paragraphs' => ['Eine Kantine oder Gemeinde verändert lokale Ernährung nicht mit einer einzigen Bestellung. Angebot, Menüs, Mengen und Logistik müssen zusammenpassen.', 'Öffentliche Beschaffung, Gemeinschaftsküchen, Schulaktionen und lokale Veranstaltungen können Landwirtschaft sichtbarer machen.', 'Bürgerinnen und Bürger können klare Menüinformationen verlangen, lokale Märkte unterstützen und Produzenten, Küchen und Eltern zusammenbringen.'],
                        'key_points' => ['Regelmäßige Absatzwege helfen Produzenten bei der Organisation.', 'Gemeinschaftsverpflegung braucht strengere Logistik als Familieneinkauf.', 'Pädagogik erleichtert saisonalere Menüs.'],
                        'citizen_actions' => ['Eine saisonale Menüwoche in Schule oder Verein vorschlagen.', 'Gemeinden nach Kriterien für Lebensmitteleinkäufe fragen.', 'Produzenten, Küchenpersonal und Eltern gemeinsam diskutieren lassen.'],
                        'pedagogical_sequence' => ['Akteure einer Gemeinschaftsmahlzeit darstellen.', 'Zwänge wie Menge, Normen, Preis, Allergien und Ausstattung erkennen.', 'Eine Absicht in klare Einkaufskriterien übersetzen.', 'Eine begrenzte, messbare erste Aktion bauen.'],
                        'workshop' => [
                            'title' => 'Ein Kantinenmenü saisonal umarbeiten',
                            'duration' => '50 Minuten',
                            'objective' => 'Zielkonflikte einer Kantine mit lokalen Produkten verstehen.',
                            'steps' => ['Ein bestehendes Menü wählen.', 'Zwei Zutaten durch saisonale lokale Alternativen ersetzen.', 'Kosten, Zubereitung, Lagerung, Akzeptanz und Allergene prüfen.', 'Eine kurze Empfehlung formulieren.'],
                            'debrief' => 'Erfolgreiche Kantinenumstellung hängt ebenso von Organisation wie von gutem Willen ab.',
                        ],
                        'discussion_questions' => ['Welche Kriterien kann eine Gemeinde öffentlich machen?', 'Wie verhindert man, dass ein Projekt nur an Einzelpersonen hängt?', 'Welche Rolle spielt Pädagogik für Kinder und Familien?'],
                        'teacher_notes' => ['Professionelle Zwänge von Küchen und Verwaltung sichtbar machen.', 'Schrittweise Aktionen aufwerten.', 'Ernährung mit Gesundheit, Gebiet, Verschwendung und lokaler Wirtschaft verbinden.'],
                    ],
                ],
                'references' => [
                    ['label' => 'Wallonisches Landwirtschaftsportal - Kurze Lieferketten', 'url' => 'https://agriculture.wallonie.be/home/groupements-et-conseils/diversification/circuits-courts-vente-directe-a-la-ferme.html'],
                    ['label' => 'APAQ-W - Kurze Lieferketten', 'url' => 'https://www.apaqw.be/fr/circuits-courts'],
                    ['label' => 'APAQ-W - Barometer lokaler Produkte', 'url' => 'https://www.apaqw.be/fr/node/11388'],
                ],
            ],
            [
                'id' => 'climat-biodiversite-pratiques-agricoles',
                'title' => 'Klima, Biodiversität und landwirtschaftliche Praktiken',
                'subtitle' => 'Hecken, Wiesen, Zwischenfrüchte, Öko-Regelungen und Agrarumweltmaßnahmen mit Diensten für das Gebiet verbinden.',
                'audience' => 'Interessierte Bürgerinnen und Bürger, Lehrkräfte, lokale Gruppen, Gemeinden, Umwelt- und Agrarvereine.',
                'duration' => 'Geführte Lektüre: 25 bis 35 Minuten',
                'illustration' => '/assets/img/dossier-climat-biodiversite.png',
                'illustration_alt' => 'Pädagogische Grafik einer Agrarlandschaft mit Hecken, Bäumen, Kulturen und Biodiversitätselementen.',
                'learning_objectives' => [
                    'Verstehen, wie Landschaftselemente Bestäubung, Nützlinge, Böden und ökologische Kontinuitäten unterstützen.',
                    'Klimaanpassung, Verringerung von Wirkungen und Umweltleistungen unterscheiden.',
                    'Grüne GAP-Hilfen als geregelte Instrumente mit Zielen, Zwängen und Kontrollen lesen.',
                    'Ein nuanciertes Urteil über Praktiken entwickeln.',
                ],
                'pedagogical_use' => [
                    'Mit Landschaftsbeobachtung beginnen.',
                    'Jedes Element mit einem möglichen Dienst verbinden und Bedingungen diskutieren.',
                    'Freiwillige Praktiken, Pflichten, Jahreszahlungen und mehrjährige Verpflichtungen vergleichen.',
                    'Eine ausgewogene Schlussfolgerung formulieren.',
                ],
                'activity_kit' => [
                    'Fotos unterschiedlicher Agrarlandschaften.',
                    'Karten zu Umweltleistungen: Bestäubung, Zuflucht, Infiltration, Schatten, Kohlenstoff, Schädlingsregulierung.',
                    'Vereinfachte fiches zu Öko-Regelungen, Agrarumweltmaßnahmen, Hecken, Wiesen und Zwischenfrüchten.',
                    'Analysetabelle: Praxis, Ziel, Kosten, Dauer, Nachweis, Grenze.',
                ],
                'evaluation' => [
                    'Jede Praxis mit einem Umweltdienst und einer Grenze verbinden.',
                    'Hilfe, Pflicht, Kompensation und Investition unterscheiden lassen.',
                    'Ein Landschaftsfoto mit sichtbaren Nachweisen und fehlenden Informationen analysieren.',
                    'Mit einem argumentierten Satz ohne Idealisierung und Pauschalurteil abschließen.',
                ],
                'vocabulary' => ['Agroökologie', 'Nützlinge im Pflanzenbau', 'Funktionale Biodiversität', 'Öko-Regelung', 'Lebende Hecke', 'Agrarumwelt- und Klimamaßnahmen', 'Dauergrünland', 'Kohlenstoffbindung', 'Ökosystemleistungen', 'Agroökologischer Wandel'],
                'chapters' => [
                    [
                        'id' => 'biodiversite-utile',
                        'title' => 'Biodiversität, die Landwirtschaft unterstützt',
                        'summary' => 'Biodiversität ist nicht nur ein Naturwert. Sie kann Bestäubung, Schädlingsregulierung und Bodenleben unterstützen.',
                        'paragraphs' => ['In Agrarlandschaften hängt nützliche Biodiversität von Lebensräumen ab: Hecken, Blühstreifen, Wiesen, Tümpel, Wegränder, Bäume, lebendige Böden und vielfältige Kulturen.', 'Nützlinge, Bestäuber und Bodenorganismen ersetzen nicht jeden Eingriff, können aber Gleichgewichte stabilisieren.', 'Eine produktive Farm kann ökologische Infrastruktur aufnehmen, wenn Zeit, Regeln, Kosten und Gebietskohärenz berücksichtigt werden.'],
                        'key_points' => ['Funktionale Biodiversität leistet konkrete Dienste.', 'Lebensräume müssen vernetzt sein.', 'Wirkungen werden langfristig und lokal bewertet.'],
                        'citizen_actions' => ['Hecken- und Blühstreifenprojekte unterstützen, wenn Pflege vorgesehen ist.', 'Nicht gemähte Zonen nicht vorschnell als Vernachlässigung deuten.', 'Biodiversität, Landwirtschaft und Ernährung in lokalen Aktionen verbinden.'],
                        'pedagogical_sequence' => ['Ein Landschaftsfoto betrachten und Lebensräume listen.', 'Jeden Lebensraum mit einer Rolle verbinden.', 'Funktionale Biodiversität erklären.', 'Bedingungen für Wirksamkeit diskutieren.'],
                        'workshop' => [
                            'title' => 'Einen Hof nützlingsfreundlicher zeichnen',
                            'duration' => '45 Minuten',
                            'objective' => 'Verstehen, dass nützliche Biodiversität ein Netz von Lebensräumen braucht.',
                            'steps' => ['Einen einfachen Hofplan verteilen.', 'Drei Elemente ergänzen: Hecke, Blühstreifen, Tümpel, Wiese oder Baum.', 'Jeden Zusatz mit Dienst und Pflegezwang begründen.', 'Elemente zu einer ökologischen Kontinuität verbinden.'],
                            'debrief' => 'Ein Biodiversitätselement wirkt besser, wenn es verbunden, gepflegt und mit Arbeit kompatibel ist.',
                        ],
                        'discussion_questions' => ['Warum kann eine ungemähte Zone nützlich sein?', 'Welche Praktiken stärken Biodiversität ohne Produktion zu verhindern?', 'Wie misst man ökologischen Nutzen jenseits des visuellen Eindrucks?'],
                        'teacher_notes' => ['Biodiversität als Teil des Produktionssystems darstellen.', 'Bemerkenswerte, gewöhnliche und funktionale Biodiversität unterscheiden.', 'Pflegeaufwand von Hecken, Streifen und Wiesen erwähnen.'],
                    ],
                    [
                        'id' => 'pratiques-climat',
                        'title' => 'Landwirtschaftliche Praktiken im Klimawandel',
                        'summary' => 'Betriebe passen sich über bedeckte Böden, Grünland, Futterautonomie, Energieeffizienz und Diversifizierung an.',
                        'paragraphs' => ['Der Klimawandel verändert Bezugspunkte: Trockenheit, Starkregen, Hitze, Wasserstress und Kosten.', 'Zwischenfrüchte, Dauergrünland, Hecken, Fruchtfolgen, Sortenwahl, Rotationsweide, Methanisierung oder weniger Betriebsmittel können Resilienz stärken.', 'Der Wandel braucht Versuche, Investitionen, Beratung und ausreichende Vergütung.'],
                        'key_points' => ['Klimawandel verbindet Anpassung und Wirkungsreduktion.', 'Ergebnisse müssen bei Wasser, Boden, Emissionen, Kosten, Einkommen und Arbeitsbelastung messbar sein.', 'Diversifizierung kann absichern, erhöht aber Komplexität.'],
                        'citizen_actions' => ['Nach bereits umgesetzten Praktiken fragen statt nur nach einem Label.', 'Produkte aus Systemen unterstützen, die Zwänge und Fortschritte erklären.', 'Lokale Ansätze fördern, die Produzenten, Gemeinden, Schulen und Konsumenten verbinden.'],
                        'pedagogical_sequence' => ['Klimawirkungen auf einen Betrieb sammeln.', 'Antworten in Anpassung und Wirkungsreduktion sortieren.', 'Mehrere Hebel je nach Betriebstyp vergleichen.', 'Kosten, Risiko, Einkommen und Akzeptanz sichtbar machen.'],
                        'workshop' => [
                            'title' => 'Drei Hebel für einen Beispielbetrieb wählen',
                            'duration' => '50 Minuten',
                            'objective' => 'Einen Wandel anhand eines konkreten Kontextes statt mit Einheitslösung begründen.',
                            'steps' => ['Einen fiktiven Betrieb beschreiben.', 'Drei Praktiken auswählen.', 'Nutzen, Grenze und Erfolgsbedingung notieren.', 'Messpunkte nach einem Jahr festlegen.'],
                            'debrief' => 'Eine Praxis wird glaubwürdig, wenn Ziel, Kontext, Kosten und Indikator klar sind.',
                        ],
                        'discussion_questions' => ['Warum passt eine Lösung nicht zu jedem Betrieb?', 'Welche Indikatoren zeigen echten Fortschritt?', 'Wie können Konsumenten Wandel unterstützen, ohne sofortige Perfektion zu verlangen?'],
                        'teacher_notes' => ['Mit Kompromissen statt abstrakten Best-Practice-Listen arbeiten.', 'Klima, Wirtschaft und Arbeitsbelastung verbinden.', 'Diversifizierung von Absatz und Einkommen erwähnen.'],
                    ],
                    [
                        'id' => 'pac-maec-eco-regimes',
                        'title' => 'GAP, Agrarumweltmaßnahmen und Öko-Regelungen',
                        'summary' => 'Einige Agrarhilfen vergüten Umwelt- oder Klimapraktiken, unterliegen aber klaren Regeln.',
                        'paragraphs' => ['Die Gemeinsame Agrarpolitik umfasst Einkommen, Pflichten und Instrumente für Klima, Landschaft, Böden, Wasser und Biodiversität.', 'Öko-Regelungen sind jährliche Verpflichtungen, Agrarumwelt- und Klimamaßnahmen oft gezielter und länger.', 'Eine Hilfe ist nicht automatisch Privileg: Sie kann Kosten, Mehraufwand, Risiko oder einen Dienst für das Gebiet ausgleichen.'],
                        'key_points' => ['Grüne Hilfen sind durch Pflichtenhefte geregelt.', 'Praktiken müssen dokumentiert und kontrollierbar sein.', 'Öffentliche Verständlichkeit braucht Ziele und Ergebnisse.'],
                        'citizen_actions' => ['Fragen: Welcher Dienst wird vergütet und wie geprüft?', 'Hilfe, Einkommen, Kompensation und Investition unterscheiden.', 'Territoriale Ansätze unterstützen, die Ergebnisse verständlich machen.'],
                        'pedagogical_sequence' => ['GAP als Rahmen von Hilfen, Regeln und Ausrichtungen vorstellen.', 'Konditionalität, jährliche Öko-Regelung, gezielte Maßnahme und Investition unterscheiden.', 'Ein Beispiel analysieren.', 'Über öffentliche Verständlichkeit diskutieren.'],
                        'workshop' => [
                            'title' => 'Eine grüne Hilfe wie einen Vertrag lesen',
                            'duration' => '40 Minuten',
                            'objective' => 'Verstehen, dass eine Umweltzahlung eine definierte Verpflichtung mit Ziel, Zwang und Kontrolle vergütet.',
                            'steps' => ['Eine vereinfachte Maßnahme wählen.', 'Ziel, Begünstigte, Verpflichtung und Nachweis markieren.', 'Festlegen, was kompensiert wird.', 'Eine klare Erklärung für Nichtfachleute formulieren.'],
                            'debrief' => 'Eine grüne Hilfe wird verständlicher, wenn Dienst und betriebliche Verpflichtung erklärt werden.',
                        ],
                        'discussion_questions' => ['Wie unterscheidet man Einkommenshilfe und Umweltkompensation?', 'Was sollte verständlicher veröffentlicht werden?', 'Welche Grenzen hat eine Bewertung nur über den Titel der Hilfe?'],
                        'teacher_notes' => ['Beispiele je nach Kampagnenjahr aktualisieren.', 'Hilfen nicht automatisch als wirksam darstellen.', 'Hilfen mit realen Feldzwängen verbinden.'],
                    ],
                ],
                'references' => [
                    ['label' => 'SPW Landwirtschaft - Öko-Regelungen GAP 2023-2027', 'url' => 'https://agriculture.wallonie.be/home/aides/pac-2023-2027-description-des-interventions/eco-regimes.html'],
                    ['label' => 'Europäische Kommission - GAP-Strategieplan Belgien Wallonie', 'url' => 'https://agriculture.ec.europa.eu/cap-my-country/cap-strategic-plans/belgium-wallonia_en'],
                    ['label' => 'Natagriwal - Agrarumweltmaßnahmen', 'url' => 'https://www.natagriwal.be/maec/'],
                ],
            ],
        ],
        'resources' => [
            [
                'id' => 'visites-pedagogiques',
                'title' => 'Pädagogische Hofbesuche',
                'description' => 'Höfe finden und Besuche für Gruppen oder Schulen sinnvoll vorbereiten.',
                'overview' => 'Eine Hofbesichtigung mit klarem Lernziel, sicheren Regeln und nutzbarer Auswertung organisieren.',
                'for' => 'Schulen, Jugendvereine, Kulturzentren, Familien, Naturanimateure und Gemeinden.',
                'verification_prompts' => ['Sind Zeiten, Zugang, Sanitäranlagen, verbotene Zonen, Allergien und Sicherheitsregeln bestätigt?', 'Welches Lernziel wird nach dem Besuch überprüft?', 'Welche Fotos, Notizen oder Produktionen dürfen ohne Genehmigungsproblem genutzt werden?'],
                'continuous_content' => 'Ein Hofbesuch sollte mehr sein als ein angenehmer Ausflug. Er wird nützlich, wenn die Gruppe weiß, was beobachtet wird, welche Regeln gelten, welche Fragen sie stellt und wie die Beobachtungen später genutzt werden.',
                'content_blocks' => [
                    ['title' => 'Vor dem Besuch vorbereiten', 'items' => ['Ein Lernziel je Gruppe festlegen.', 'Hof nach Zugänglichkeit, Hygiene, Sicherheit und Kapazität auswählen.', 'Rollen der Begleitpersonen klären.', 'Genehmigungen, Gesundheitsinfos und Notfallkontakte sammeln.']],
                    ['title' => 'Ablauf strukturieren', 'text' => 'Eine stabile Sequenz folgt fünf Momenten: Einführung, Beobachtung, Praxis, Zusammenfassung und Anschlussarbeit. Jeder Teil bleibt kurz und vorhersehbar.'],
                    ['title' => 'Nach dem Besuch nutzen', 'items' => ['Fünf-Minuten-Bericht mit zentralem Begriff erstellen.', 'Fotos und Notizen für Unterricht oder Workshop sichern.', 'Kreative Auswertung als Plakat, Heft oder Audio aufnehmen.']],
                ],
                'steps' => ['Lernziele und Zielgruppe klären.', 'Hof mit Sicherheit und Zugangsbedingungen auswählen.', 'Ablauf mit Partnern bauen.', 'Genehmigungen, Logistik und Material finalisieren.', 'Regeln und Erwartungen kommunizieren.', 'Besuch mit kurzen aktiven Sequenzen durchführen.', 'Lernen auswerten.', 'Verbesserungen notieren.'],
                'checklist' => ['Lernziele geteilt.', 'Ausreichende Begleitung vorhanden.', 'Genehmigungen und Gesundheitsdaten verfügbar.', 'Sicherheitsregeln erklärt.', 'Transport und Notfallplan geprüft.', 'Feldmaterial vorbereitet.', 'Auswertung geplant.'],
                'learning_objectives' => ['Den Weg eines Lebensmittels vom Feld zum Teller verstehen.', 'Rolle von Boden, Wasser, Biodiversität und Klima erkennen.', 'Landwirtschaftliche Berufe entdecken.', 'Produktion, Verarbeitung und Verteilung unterscheiden.', 'Labels, Herkunft und Kosten kritisch lesen.'],
                'recommended_program' => ['00:00-00:10 - Empfang und Regeln.', '00:10-00:40 - Rundgang.', '00:40-01:10 - Workshops.', '01:10-01:25 - Pause und Notizen.', '01:25-01:50 - Fokus vom Hof zum Teller.', '01:50-02:00 - Abschluss.'],
                'age_adaptations' => ['Kindergarten: sinnlicher Rundgang.', 'Primarschule: geführte Beobachtung.', 'Sekundarstufe: Daten und Diskussion.', 'Erwachsene: Konsum, Budget, Qualität und Saison.'],
                'pedagogical_activities' => ['Kulturen erkennen.', 'Lebensmittelweg nachverfolgen.', 'Rollenspiel Produzent-Verarbeiter-Verkäufer-Konsument.', 'Bodenstruktur und Wasserrückhalt testen.', 'Anti-Verschwendungs-Kochatelier.'],
                'risk_prevention' => ['Sperrzonen um Maschinen und sensible Tiere.', 'Händewaschen vor und nach Manipulationen.', 'Verstärkte Aufsicht an Risikopunkten.', 'Innenraumplan bei Regen oder Hitze.', 'Allergien und Ernährungseinschränkungen bestätigen.'],
                'budget_items' => ['Transport.', 'Empfangs- und Animationspauschale.', 'Pädagogische Unterlagen.', 'Feldmaterial und Reinigung.', 'Reserve von 10 bis 15 Prozent.'],
                'evaluation_method' => ['Vorher-nachher-Fragebogen.', 'Gemeinsame Produktion als Plakat, Audio oder Logbuch.', 'Selbsteinschätzung.', 'Rückmeldung des Betriebs.', 'Organisatorische Bilanz mit nächstem Schritt.'],
            ],
            [
                'id' => 'formations-metiers',
                'title' => 'Ausbildungen und Berufe',
                'description' => 'Wege in Landwirtschaft und Agrarlebensmittelbereich erkunden.',
                'overview' => 'Orientierungspunkte, um Berufe, Ausbildungen, Praxiseinblicke und erwartete Kompetenzen zu vergleichen.',
                'for' => 'Schülerinnen und Schüler, Studierende, Erwachsene in Neuorientierung, Arbeitssuchende, Lehrkräfte und Berufsberatung.',
                'verification_prompts' => ['Ist Ausbildung oder Zertifizierung für den Zielberuf anerkannt?', 'Welche Arbeitszeiten, Wege, körperlichen Zwänge und Vergütung müssen getestet werden?', 'Welche kurze Praxiserfahrung prüft, ob der Beruf zum Projekt passt?'],
                'continuous_content' => 'Eine Orientierung in Richtung Landwirtschaft braucht mehr als eine Ausbildungsliste. Der Berufswunsch muss mit Arbeitszeiten, Technik, körperlichen Anforderungen, lokalen Absatzwegen und nötiger Autonomie abgeglichen werden.',
                'steps' => ['Berufsfeld wählen.', 'Eigenes Profil und Zwänge prüfen.', 'Passende Ausbildungswege identifizieren.', 'Voraussetzungen und Absatzchancen prüfen.', 'Kurzpraktikum oder Besuch organisieren.', 'Bewerbungsunterlagen bauen.', 'Finanzierung suchen.', 'Sechs- bis Zwölfmonatsplan festlegen.'],
                'checklist' => ['Zwei bis drei realistische Berufsspuren geklärt.', 'Vorhandene und fehlende Kompetenzen dokumentiert.', 'Ausbildungen objektiv verglichen.', 'Bewerbungs- und Praktikumskalender erstellt.', 'Finanzierung geprüft.', 'Erste Feldkontakte vorhanden.', 'Erster Schritt innerhalb von 30 Tagen geplant.'],
                'job_families' => ['Pflanzenproduktion.', 'Tierhaltung.', 'Lebensmittelverarbeitung.', 'Vermarktung und Logistik.', 'Technische Beratung und Agrartechnik.', 'Querschnittsfunktionen wie Management, Qualität und Rückverfolgbarkeit.'],
                'training_paths' => ['Berufsbildende Sekundarstufe.', 'Bachelor oder Kurzstudium in Agronomie, Technik, Qualität oder Handel.', 'Ingenieur- und Agrarstudien.', 'Duale Ausbildung.', 'Kurze Weiterbildungsmodule.', 'Anerkennung erworbener Erfahrung.'],
                'key_skills' => ['Technik in Pflanzenbau, Tierhaltung oder Verarbeitung.', 'Digitale Werkzeuge und Datenpflege.', 'Kostenrechnung und Betriebssteuerung.', 'Organisation und Kommunikation.', 'Sicherheit, Hygiene, Umwelt und Tierwohl.'],
                'certifications' => ['Lebensmittelsicherheit und HACCP.', 'Maschinen- und Arbeitssicherheitsnachweise.', 'Qualitäts- und Umweltzertifizierungen.', 'Spezialmodule zu Bewässerung, Schnitt, Käserei oder Direktverkauf.'],
                'financing_options' => ['Duale Ausbildung.', 'Regionale Hilfen und Neuorientierungsprogramme.', 'Arbeitgeber- oder Kompetenzfondsfinanzierung.', 'Stipendien, Mobilitätshilfen und soziale Unterstützung.'],
                'application_tips' => ['Lebenslauf mit konkreten Nachweisen anpassen.', 'Übertragbare Kompetenzen sichtbar machen.', 'Drei Feldbeispiele für Gespräche vorbereiten.', 'Aktuelle Agrarthemen kennen.'],
                'salary_factors' => ['Qualifikationsniveau.', 'Betriebs- oder Unternehmensform.', 'Regionale Nachfrage.', 'Saison, Arbeitszeiten und Vielseitigkeit.'],
                'mobility_paths' => ['Techniker zu Teamleitung.', 'Direktverkauf zu Handelsentwicklung.', 'Produktion zu Qualität oder Rückverfolgbarkeit.', 'Betrieb zu Beratung oder Ausbildung.'],
                'action_plan_90_days' => ['Tage 1-15: Profil und Zielberufe klären.', 'Tage 16-30: Kurzpraktikum und Bewerbungsunterlagen.', 'Tage 31-60: Bewerbungen und Finanzierung.', 'Tage 61-90: Start in Ausbildung, Job oder Praktikum.'],
            ],
            [
                'id' => 'consommation-responsable',
                'title' => 'Verantwortungsvoller Konsum',
                'description' => 'Praktische Orientierung für nachhaltigere Lebensmitteleinkäufe.',
                'overview' => 'Eine konkrete Methode, um Einkäufe zu verbessern, ohne unerreichbare Perfektion zu versprechen.',
                'for' => 'Haushalte, Studierende, Familien, Verbrauchervereine, Einkaufsgemeinschaften, Gemeinden und Bildungseinrichtungen.',
                'verification_prompts' => ['Welche Änderung ist vier Wochen tragbar?', 'Wird der Preis pro Kilo, Portion oder Mahlzeit verglichen?', 'Sind Erzeugungsort und Verarbeitungsort bekannt?'],
                'continuous_content' => 'Verantwortungsvoll einkaufen beginnt im realen Haushalt: Budget, Kochzeit, weggeworfene Reste, nahe verfügbare Produkte und Gewohnheiten, die dauerhaft funktionieren.',
                'steps' => ['Gewohnheiten über Bons und Abfälle analysieren.', 'Messbare Ziele setzen.', 'Fünf bis sieben Mahlzeiten planen.', 'Einkaufsliste strukturieren.', 'Kilopreise und Etiketten lesen.', 'Kochen und lagern.', 'Reste verwerten.', 'Monatlich anpassen.'],
                'checklist' => ['Wochenziele definiert.', 'Menü mit Alternativen geplant.', 'Einkaufsliste priorisiert.', 'Frischeprodukte realistisch geplant.', 'Restegerichte vorbereitet.', 'Lager organisiert.', 'Ausgaben und Abfälle verfolgt.'],
                'purchase_strategy' => ['60/30/10-Regel nutzen: Grundprodukte, nützliche Verarbeitung, Genusskäufe.', 'Saison und lokale Ketten priorisieren, wenn Preis und Qualität passen.', 'Mehrere Einkaufsorte kombinieren.', 'Mengen nur für haltbare Produkte erhöhen.'],
                'label_reading' => ['Zertifiziertes Label von Marketingversprechen trennen.', 'Kontrollstelle und abgedeckten Produktteil prüfen.', 'Label mit Saison, Herkunft, Zutaten und Kilopreis kombinieren.'],
                'seasonal_planning' => ['Winter: Lagergemüse und Hülsenfrüchte.', 'Frühling: junge Gemüse und einfache Gerichte.', 'Sommer: frisches Obst und kurze Haltbarkeit.', 'Herbst: Konservieren, Einfrieren und Vorräte.'],
                'anti_waste_playbook' => ['Wöchentliches Restegericht einplanen.', 'Reste mit Datum und Portion beschriften.', 'Überschüsse in Suppen, Quiches, Kompott oder Saucen verwandeln.', 'Portionen an tatsächlichen Appetit anpassen.'],
                'nutrition_balance' => ['Teller aufteilen: Hälfte Pflanzen, Viertel Stärke, Viertel Protein.', 'Ballaststoffe und Hülsenfrüchte stärken.', 'Ultra-verarbeitete Produkte begrenzen.', 'Tierische und pflanzliche Proteine variieren.'],
                'budget_optimisation' => ['Kilopreis systematisch vergleichen.', 'Nur stabile Produkte in größeren Mengen kaufen.', 'Einkaufsgemeinschaften nutzen.', 'Durchschnittskorb, Kosten pro Mahlzeit und Verschwendung verfolgen.'],
                'kpi_tracking' => ['Anteil saisonaler Produkte.', 'Anteil lokaler oder kurzer Ketten.', 'Geschätzter Wert weggeworfener Lebensmittel.', 'Anzahl Restegerichte.', 'Kosten pro Mahlzeit.'],
            ],
            [
                'id' => 'calendrier-marches-locaux',
                'title' => 'Kalender lokaler Märkte',
                'description' => 'Produzentenmärkte und Hofverkaufsstellen erkennen.',
                'overview' => 'Märkte und Hofverkäufe in eine realistische Einkaufsroutine übersetzen.',
                'for' => 'Einwohnerinnen und Einwohner, Zugezogene, lokale Gemeinden.',
                'verification_prompts' => ['Ist das Produkt lokal erzeugt, lokal verarbeitet oder nur lokal verkauft?', 'Sind Zeiten, Saisonpräsenz und Zahlungsmittel aktuell bestätigt?', 'Welche Alternative gibt es bei Ausfall, Abwesenheit oder zu hohem Preis?'],
                'continuous_content' => 'Ein lokaler Markt ist nur nützlich, wenn er in den Alltag passt. Diese Seite hilft, Orte, Tage, regelmäßige Produzenten, saisonale Produkte und Ausweichlösungen zu planen.',
                'steps' => ['Wöchentliche Märkte nahe Wohn- oder Arbeitsort listen.', 'Saisonmärkte und offene Hoftage ergänzen.', 'Direktverkäufer und Spezialitäten notieren.', 'Einkaufsorte rotieren.', 'Kalender mit Nachbarn oder Vereinen teilen.'],
                'checklist' => ['Drei nahe Märkte identifiziert.', 'Zeitfenster passen zum Alltag.', 'Produzentenkontakte gespeichert.', 'Alternative bei Ausfall vorgesehen.'],
            ],
            [
                'id' => 'aides-accompagnement',
                'title' => 'Hilfen und Begleitung',
                'description' => 'Unterstützungsinstrumente für den agroökologischen Wandel verstehen.',
                'overview' => 'Vorbereitungstabelle, um ein Agrarprojekt zu strukturieren, Förderfähigkeit zu prüfen und Fehler vor Antragstellung zu vermeiden.',
                'for' => 'Aktive Betriebe, Junglandwirte, Projektträger, Kooperativen, Gemeinden, Beratungsstellen und ländliche Vereine.',
                'verification_prompts' => ['Dürfen Ausgaben vor Bewilligung starten?', 'Welche Kriterien, Obergrenzen, Fristen und Nachweise sind schriftlich bestätigt?', 'Wer liest das Dossier vor Einreichung gegen?'],
                'continuous_content' => 'Eine Hilfe ersetzt kein solides Projekt. Vor Antragstellung müssen Ziel, Regeln, Kosten, Liquidität und Nachweise geklärt werden.',
                'steps' => ['Bedarf präzise formulieren.', 'Ausgangslage mit Indikatoren erfassen.', 'Finanzierer und Begleiter kartieren.', 'Förderfähigkeit prüfen.', 'Investitionsplan bauen.', 'Unterlagen vorbereiten.', 'Erwartete Wirkungen beschreiben.', 'Fristgerecht einreichen.', 'Umsetzung regelkonform sichern.', 'Reporting organisieren.'],
                'checklist' => ['Projektziel in einem Satz.', 'Vollständiges Budget mit Angeboten.', 'Finanzierungsplan.', 'Förderkriterien geprüft.', 'Dossier gegengelesen.', 'Meilensteine geplant.', 'Archivierung organisiert.', 'Ergebnisindikatoren definiert.', 'Kontaktperson benannt.', 'Risikoplan vorbereitet.'],
                'eligible_projects' => ['Modernisierung.', 'Agroökologischer Wandel.', 'Energieeffizienz.', 'Diversifizierung und Verarbeitung.', 'Innovation und Digitales.', 'Kollektive Aktionen.'],
                'required_documents' => ['Identität und Rechtsform.', 'Betriebsnummern und aktuelle Bescheinigungen.', 'Bilanzen oder Prognosen.', 'Angebote, Pläne und technische Beschreibungen.', 'Flächennachweise.', 'Regulatorische Konformität.', 'Motivationsnotiz.'],
                'timeline' => ['Woche 1-2: Bedarf klären.', 'Woche 3-6: Dossier bauen.', 'Woche 7-8: externe Prüfung und Einreichung.', 'Monat 3-6: Prüfung und Nachfragen.', 'Nach Bewilligung: Umsetzung und Nachweise.'],
                'common_pitfalls' => ['Ausgaben vor Bewilligung.', 'Unvollständiges Dossier.', 'Unklare Ziele.', 'Unterschätzte Fristen.', 'Fehlender Liquiditätsplan.'],
                'support_contacts' => ['Regionale Agrarschalter.', 'Management- und technische Beratung.', 'Lokale Strukturen für ländliche Entwicklung.', 'Berufsnetzwerke und Erfahrungsaustausch.'],
            ],
            [
                'id' => 'decouvrir-labels',
                'title' => 'Labels verstehen',
                'description' => 'Wichtige Qualitäts-, Herkunfts- und Nachhaltigkeitslabels vergleichen.',
                'overview' => 'Leseschlüssel, um kontrollierte Zertifizierung, Herkunft, Marketingversprechen und wirklich nützliche Kriterien zu unterscheiden.',
                'for' => 'Konsumentinnen und Konsumenten, Workshop-Leitungen, Bildungseinrichtungen.',
                'verification_prompts' => ['Ist es ein kontrolliertes Label, eine private Marke, eine Herkunftsangabe oder ein Versprechen?', 'Wer kontrolliert das Pflichtenheft?', 'Welche Informationen fehlen: Saison, Kilopreis, Zutaten, Herkunft oder Verarbeitung?'],
                'continuous_content' => 'Ein Label erklärt nie alles allein. Man muss prüfen, was es verspricht, wer kontrolliert, welcher Teil des Produkts betroffen ist und welche Informationen fehlen.',
                'steps' => ['Versprechen des Labels identifizieren.', 'Unabhängige Kontrolle prüfen.', 'Produkte derselben Kategorie vergleichen.', 'Nicht zertifizierte Marketingangaben erkennen.', 'Label mit Saison, Nähe und Budget kombinieren.'],
                'checklist' => ['Mindestens drei Labels verstanden.', 'Zertifizierung und Marketingargument unterschieden.', 'Eigene Auswahlkriterien formuliert.', 'Einkaufsgewohnheit daran ausgerichtet.'],
            ],
            [
                'id' => 'boite-a-outils-anti-gaspillage',
                'title' => 'Anti-Verschwendungs-Werkzeugkasten',
                'description' => 'Tipps, um frische Produkte besser zu lagern, zu kochen und zu verwerten.',
                'overview' => 'Einfache Werkzeuge, um Verluste zu erkennen, Vorräte zu organisieren, Reste zu kochen und Fortschritte zu messen.',
                'for' => 'Familien, Studierende, Gemeinschaftsküchen und Vereine.',
                'verification_prompts' => ['Welche Lebensmittelkategorie wird am häufigsten weggeworfen und warum?', 'Respektiert die Lösung Kühlkette, Hygiene und Haltbarkeit?', 'Welcher einfache Indikator wird verfolgt?'],
                'continuous_content' => 'Lebensmittelverschwendung wird zuerst durch Beobachtung korrigiert: Welche Produkte bleiben im Kühlschrank liegen, welche Portionen sind falsch, welche Daten werden übersehen?',
                'steps' => ['Lebensmittel nach Verderblichkeit sortieren.', 'FIFO-Regel nutzen.', 'Wöchentliches Resterezept einplanen.', 'Portioniert und beschriftet einfrieren.', 'Nicht essbare Bioabfälle kompostieren, wenn möglich.'],
                'checklist' => ['Wöchentliche Kühlschrankinventur.', 'Reste mindestens einmal pro Woche genutzt.', 'Lagerplan sichtbar.', 'Lebensmittelabfälle monatlich verfolgt.'],
            ],
            [
                'id' => 'parcours-pedagogiques',
                'title' => 'Pädagogische Lernpfade',
                'description' => 'Ressourcen für Lehrkräfte und Familien zu Ernährung, Landwirtschaft und Jahreszeiten.',
                'overview' => 'Modulare Lernpfade für Ernährung, Jahreszeiten, Agrarberufe und kritisches Denken mit unterschiedlichen Altersgruppen.',
                'for' => 'Lehrkräfte, Erziehende, Eltern und Wissenschaftsvermittler.',
                'verification_prompts' => ['Welche Leitfrage strukturiert den Lernpfad?', 'Sind Wortschatz, Dauer und Abstraktion passend?', 'Welche Auswertung zeigt Verständnis?'],
                'continuous_content' => 'Ein guter Lernpfad vermeidet zwei Fehler: Informationen ohne Aktivität sammeln oder angenehme Animation ohne klares Lernen anbieten.',
                'steps' => ['Niveau nach Alter wählen.', 'Kurze Sequenzen planen: verstehen, beobachten, üben, auswerten.', 'Medien, fiches, einfache Experimente und Feldbesuch kombinieren.', 'Mit Mini-Projekt auswerten.', 'Ergebnisse für nächstes Jahr sichern.'],
                'checklist' => ['Lernziele formuliert.', 'Material und Aktivitäten altersgerecht.', 'Auswertungsmoment geplant.', 'Einfache Abschlussprüfung vorbereitet.'],
            ],
        ],
    ];
}
