<?php

declare(strict_types=1);

/**
 * @return array<string, mixed>
 */
function getPortalData(): array
{
    return [
        'site' => [
            'title' => 'MyAgri — Portail citoyen',
            'subtitle' => 'Comprendre l’agriculture wallonne : alimentation, territoires, environnement, économie et métiers.',
            'updated_at' => '25 avril 2026',
        ],
        'quickFacts' => [
            [
                'title' => 'Un enjeu quotidien',
                'content' => 'L’agriculture influence directement le prix, la qualité et la diversité de notre alimentation.',
            ],
            [
                'title' => 'Un rôle territorial',
                'content' => 'Elle structure les paysages, soutient l’emploi local et maintient la vie économique rurale.',
            ],
            [
                'title' => 'Un secteur en transition',
                'content' => 'Les fermes s’adaptent au climat, à la pression économique et aux attentes sociétales.',
            ],
            [
                'title' => 'Un moteur d’innovation',
                'content' => 'Du numérique aux nouvelles variétés, les pratiques évoluent pour produire mieux avec moins de ressources.',
            ],
            [
                'title' => 'Un lien social',
                'content' => 'Marchés, coopératives, fermes pédagogiques et circuits courts rapprochent citoyens et producteurs.',
            ],
        ],
        'pillars' => [
            ['name' => 'Produire', 'description' => 'Assurer une production fiable, diversifiée et de qualité pour répondre aux besoins alimentaires.'],
            ['name' => 'Préserver', 'description' => 'Protéger l’eau, les sols, le climat et la biodiversité pour maintenir la capacité de production sur le long terme.'],
            ['name' => 'Relier', 'description' => 'Créer du lien entre producteurs, transformateurs, distributeurs et citoyens via des filières lisibles.'],
            ['name' => 'Innover', 'description' => 'S’appuyer sur la recherche, l’expérimentation et les retours terrain pour améliorer les pratiques.'],
        ],
        'sectors' => [
            [
                'label' => 'Grandes cultures',
                'emoji' => '🌾',
                'summary' => 'Céréales, pommes de terre et betteraves occupent une place importante.',
                'enjeux' => [
                    'Gestion des risques climatiques.',
                    'Fertilité des sols et rotations.',
                    'Stabilité économique des exploitations.',
                    'Disponibilité de l’eau et maîtrise des intrants.',
                ],
                'public_actions' => [
                    'Privilégier la saisonnalité et l’origine locale.',
                    'S’informer sur les filières de transformation régionales.',
                    'Réduire le gaspillage alimentaire pour valoriser au mieux le travail agricole.',
                ],
            ],
            [
                'label' => 'Élevage bovin et laitier',
                'emoji' => '🐄',
                'summary' => 'L’élevage valorise les prairies et alimente les filières laitières et viandeuses.',
                'enjeux' => [
                    'Bien-être animal et revenu des éleveurs.',
                    'Autonomie fourragère et coûts de production.',
                    'Réduction de l’empreinte environnementale.',
                    'Transmission des fermes et renouvellement des générations.',
                ],
                'public_actions' => [
                    'Découvrir les labels et démarches qualité.',
                    'Soutenir les points de vente fermiers.',
                    'Comparer l’origine des produits laitiers et carnés pour encourager les filières locales.',
                ],
            ],
            [
                'label' => 'Maraîchage, horticulture et vergers',
                'emoji' => '🥕',
                'summary' => 'Des productions de proximité adaptées aux circuits courts.',
                'enjeux' => [
                    'Main-d’œuvre, stockage et logistique.',
                    'Irrigation et adaptation aux canicules.',
                    'Valorisation commerciale en vente directe.',
                    'Accès au foncier de proximité pour de nouveaux maraîchers.',
                ],
                'public_actions' => [
                    'Acheter en direct chez les producteurs.',
                    'Diversifier son panier avec des produits de saison.',
                    'Planifier ses menus hebdomadaires pour soutenir une consommation locale régulière.',
                ],
            ],
            [
                'label' => 'Diversification (petits fruits, houblon, viticulture)',
                'emoji' => '🍇',
                'summary' => 'Des filières émergentes créent de la valeur locale et renforcent la résilience des fermes.',
                'enjeux' => [
                    'Investissements de départ et accompagnement technique.',
                    'Structuration des débouchés locaux et touristiques.',
                    'Gestion des risques sanitaires et climatiques.',
                    'Développement de compétences en transformation et commercialisation.',
                ],
                'public_actions' => [
                    'Découvrir les produits locaux transformés (jus, bière, vin, confitures).',
                    'Visiter les exploitations qui ouvrent leurs ateliers au public.',
                    'Choisir des cadeaux alimentaires issus de producteurs régionaux.',
                ],
            ],
        ],
        'focusThemes' => [
            ['title' => 'Eau', 'details' => 'Économiser et mieux stocker l’eau pour sécuriser les productions.'],
            ['title' => 'Sols', 'details' => 'Renforcer la matière organique et limiter l’érosion.'],
            ['title' => 'Biodiversité', 'details' => 'Déployer haies, bandes fleuries et infrastructures écologiques.'],
            ['title' => 'Climat', 'details' => 'Adapter les pratiques et limiter les émissions.'],
            ['title' => 'Énergie', 'details' => 'Réduire les coûts via l’efficacité énergétique et l’autoproduction.'],
            ['title' => 'Numérique', 'details' => 'Mieux piloter les cultures et troupeaux grâce aux données de terrain.'],
        ],

        'provinces' => [
            ['name' => 'Brabant wallon', 'profile' => 'Mosaïque de cultures, maraîchage et transformation locale, avec une forte proximité des bassins de consommation.'],
            ['name' => 'Hainaut', 'profile' => 'Poids important des grandes cultures et de l’agroalimentaire, soutenu par des infrastructures logistiques structurantes.'],
            ['name' => 'Liège', 'profile' => 'Élevage, vergers et filières de valorisation de proximité, avec des initiatives dynamiques en circuits courts.'],
            ['name' => 'Luxembourg', 'profile' => 'Systèmes herbagers, forêts et élevage extensif, dans des paysages où l’équilibre entre production et nature est central.'],
            ['name' => 'Namur', 'profile' => 'Diversité de productions entre grandes cultures, élevage et maraîchage, avec un tissu d’exploitations familiales varié.'],
        ],
        'seasonalCalendar' => [
            ['season' => 'Printemps', 'focus' => 'Semis, gestion de l’eau, protection contre le gel tardif et organisation des premières récoltes.'],
            ['season' => 'Été', 'focus' => 'Récoltes précoces, irrigation ciblée, prévention du stress hydrique et gestion des pics de travail.'],
            ['season' => 'Automne', 'focus' => 'Récoltes principales, semis d’automne, couverts végétaux et préparation des sols pour l’hiver.'],
            ['season' => 'Hiver', 'focus' => 'Entretien du matériel, planification, soins aux animaux et préparation de la campagne suivante.'],
        ],
        'faq' => [
            [
                'q' => 'Pourquoi les prix agricoles sont-ils parfois instables ?',
                'a' => 'Ils dépendent à la fois des marchés mondiaux, de la météo, des coûts de l’énergie et de la transformation.',
            ],
            [
                'q' => 'Le circuit court est-il toujours possible ?',
                'a' => 'Pas pour tous les produits, mais il peut renforcer le lien local et la valeur ajoutée quand il est bien organisé.',
            ],
            [
                'q' => 'Comment sensibiliser les enfants ?',
                'a' => 'Via des visites de fermes, des ateliers alimentaires, des potagers et l’observation des saisons.',
            ],
            [
                'q' => 'Pourquoi parle-t-on autant de souveraineté alimentaire ?',
                'a' => 'Elle vise à garantir une capacité locale à produire une part significative de l’alimentation en cas de crise.',
            ],
            [
                'q' => 'Que signifie “prix juste” pour un agriculteur ?',
                'a' => 'Un prix qui couvre les coûts de production, rémunère le travail et permet d’investir dans la transition.',
            ],
            [
                'q' => 'Comment un citoyen peut-il agir sans augmenter fortement son budget ?',
                'a' => 'En privilégiant la saison, en cuisinant des produits bruts, en limitant le gaspillage et en comparant les points de vente locaux.',
            ],
            [
                'q' => 'Pourquoi les pratiques agricoles varient-elles d’une région à l’autre ?',
                'a' => 'Les choix techniques dépendent du climat, des sols, du relief, des filières présentes et des débouchés économiques locaux.',
            ],
        ],
        'glossary' => [
            ['term' => 'Agroécologie', 'definition' => 'Application de principes écologiques à la production agricole.'],
            ['term' => 'Rotation', 'definition' => 'Alternance planifiée des cultures sur une même parcelle.'],
            ['term' => 'Circuit court', 'definition' => 'Vente avec peu ou pas d’intermédiaires.'],
            ['term' => 'Prairie permanente', 'definition' => 'Prairie installée durablement, utile à l’élevage et aux écosystèmes.'],
            ['term' => 'Autonomie fourragère', 'definition' => 'Capacité d’un élevage à produire la majorité de l’alimentation de ses animaux.'],
            ['term' => 'Couvert végétal', 'definition' => 'Culture implantée entre deux cultures principales pour protéger et enrichir le sol.'],
            ['term' => 'Assolement', 'definition' => 'Répartition des différentes cultures sur les parcelles d’une exploitation pour une campagne donnée.'],
            ['term' => 'Intrants', 'definition' => 'Ensemble des produits utilisés pour produire : semences, engrais, produits de protection, énergie, aliments du bétail, etc.'],
            ['term' => 'Polyculture-élevage', 'definition' => 'Système qui combine cultures et élevage sur la même ferme pour mieux valoriser les ressources.'],
            ['term' => 'Résilience', 'definition' => 'Capacité d’une exploitation à absorber un choc (climat, prix, crise sanitaire) et à continuer de fonctionner.'],
            ['term' => 'Traçabilité', 'definition' => 'Possibilité de suivre un produit de son origine à sa vente grâce à des informations vérifiables.'],
            ['term' => 'Bilan carbone', 'definition' => 'Évaluation des émissions de gaz à effet de serre générées par une activité ou une filière.'],
            ['term' => 'Haie vive', 'definition' => 'Alignement d’arbustes et d’arbres jouant un rôle pour la biodiversité, le vent, l’eau et les paysages.'],
            ['term' => 'Filière', 'definition' => 'Chaîne d’acteurs allant de la production à la transformation puis à la distribution d’un produit agricole.'],
            ['term' => 'Valeur ajoutée', 'definition' => 'Richesse créée par la transformation, la qualité, l’origine ou le mode de commercialisation d’un produit.'],
            ['term' => 'Agriculture de précision', 'definition' => 'Utilisation d’outils numériques (capteurs, GPS, données) pour ajuster les pratiques au plus juste.'],
            ['term' => 'Agriculture biologique', 'definition' => 'Mode de production reposant sur des règles spécifiques limitant les intrants de synthèse et favorisant les équilibres naturels.'],
            ['term' => 'Agroforesterie', 'definition' => 'Association d’arbres et de cultures ou d’élevage sur une même parcelle pour renforcer les services écosystémiques.'],
            ['term' => 'AOP/IGP', 'definition' => 'Signes officiels de qualité liés à l’origine géographique et à un savoir-faire reconnu.'],
            ['term' => 'Bocage', 'definition' => 'Paysage agricole composé de parcelles entourées de haies, favorable à la biodiversité et à la protection des sols.'],
            ['term' => 'Couverts permanents', 'definition' => 'Présence continue de végétation sur le sol afin de réduire l’érosion et améliorer sa structure.'],
            ['term' => 'Cultures associées', 'definition' => 'Conduite simultanée de plusieurs espèces sur une même parcelle pour mieux utiliser les ressources.'],
            ['term' => 'Densité de chargement', 'definition' => 'Nombre d’animaux rapporté à une surface donnée, indicateur de pression sur les prairies et ressources.'],
            ['term' => 'Diversification', 'definition' => 'Ajout de nouvelles productions, activités ou circuits de vente pour sécuriser les revenus de la ferme.'],
            ['term' => 'Économie circulaire', 'definition' => 'Organisation visant à réduire les pertes de matière et d’énergie en favorisant réemploi, recyclage et valorisation locale.'],
            ['term' => 'Élevage extensif', 'definition' => 'Système d’élevage basé sur une faible densité animale et une forte valorisation des surfaces herbagères.'],
            ['term' => 'Érosion des sols', 'definition' => 'Perte de particules de sol sous l’action de l’eau ou du vent, pouvant réduire la fertilité des parcelles.'],
            ['term' => 'Fertilité du sol', 'definition' => 'Capacité d’un sol à fournir eau, nutriments et conditions favorables à la croissance des cultures.'],
            ['term' => 'Gestion intégrée des ravageurs', 'definition' => 'Approche combinant prévention, observation et interventions ciblées pour limiter les dégâts sanitaires.'],
            ['term' => 'Humus', 'definition' => 'Fraction organique stable du sol contribuant à sa structure, sa fertilité et sa capacité de rétention d’eau.'],
            ['term' => 'Irrigation raisonnée', 'definition' => 'Apport d’eau ajusté aux besoins réels des cultures pour optimiser la ressource et éviter les excès.'],
            ['term' => 'Matière organique', 'definition' => 'Ensemble des résidus végétaux et animaux en décomposition qui nourrissent la vie du sol.'],
            ['term' => 'Méthanisation', 'definition' => 'Processus biologique transformant des matières organiques en biogaz et digestat valorisable en agriculture.'],
            ['term' => 'PAC', 'definition' => 'Politique Agricole Commune de l’Union européenne, cadre d’aides, de règles et d’orientations pour l’agriculture.'],
            ['term' => 'Pâturage tournant', 'definition' => 'Méthode de gestion des prairies qui alterne les parcelles pâturées afin d’améliorer la repousse de l’herbe.'],
            ['term' => 'Pertes post-récolte', 'definition' => 'Quantités perdues entre la récolte et la consommation à cause du stockage, du transport ou de la transformation.'],
            ['term' => 'Plan de fumure', 'definition' => 'Programmation des apports fertilisants selon les besoins des cultures et les caractéristiques des sols.'],
            ['term' => 'Prix rémunérateur', 'definition' => 'Prix permettant de couvrir les coûts de production et d’assurer un revenu viable à l’exploitant.'],
            ['term' => 'Protéagineux', 'definition' => 'Cultures riches en protéines (pois, féverole, lupin, etc.) utilisées en alimentation humaine ou animale.'],
            ['term' => 'Saisonnalité', 'definition' => 'Période naturelle de production d’un aliment, influençant disponibilité, goût, coût et impact environnemental.'],
            ['term' => 'Séquestration carbone', 'definition' => 'Stockage du carbone dans les sols et la biomasse, contribuant à atténuer le changement climatique.'],
            ['term' => 'Souveraineté alimentaire', 'definition' => 'Capacité d’un territoire à organiser durablement son alimentation et à sécuriser son approvisionnement.'],
            ['term' => 'Stress hydrique', 'definition' => 'Situation où les besoins en eau des cultures dépassent les disponibilités, affectant rendement et qualité.'],
            ['term' => 'Transformation à la ferme', 'definition' => 'Valorisation des productions directement sur l’exploitation (fromage, jus, yaourt, etc.).'],
            ['term' => 'Transition agroécologique', 'definition' => 'Évolution progressive des systèmes agricoles vers des pratiques plus durables sur les plans environnemental, social et économique.'],
            ['term' => 'Zéro artificialisation nette (ZAN)', 'definition' => 'Objectif visant à limiter la consommation d’espaces naturels, agricoles et forestiers par l’urbanisation.'],
        ],
        'resources' => [
            [
                'id' => 'visites-pedagogiques',
                'title' => 'Visites pédagogiques',
                'description' => 'Trouver des fermes ouvertes au public et aux écoles.',
                'overview' => 'Guide exhaustif pour concevoir, animer et évaluer une visite pédagogique agricole : objectifs d’apprentissage, sécurité, déroulé minute par minute, activités selon l’âge, budget, communication et exploitation pédagogique après la sortie.',
                'for' => 'Écoles maternelles/primaires/secondaires, associations jeunesse, maisons de quartier, centres culturels, familles, animateurs nature et collectivités.',
                'steps' => [
                    'Cadrer les objectifs pédagogiques : alimentation, saisonnalité, biodiversité, bien-être animal, métiers, climat, eau, sol, circuits courts.',
                    'Sélectionner une ferme adaptée au public (accessibilité, capacité d’accueil, infrastructures sanitaires, zones couvertes, assurance).',
                    'Co-construire le scénario de visite avec l’exploitant : séquences, temps d’échange, manipulations, dégustation éventuelle.',
                    'Préparer les participants : notions clés, règles de sécurité, attentes comportementales, vêtements adaptés, questions à poser.',
                    'Valider la logistique complète : transport, timing, encadrement adulte/enfants, contacts d’urgence, trousse de secours.',
                    'Animer la visite avec pédagogie active : observation, manipulation, prise de notes, photos/documentation, restitution orale.',
                    'Conclure par une synthèse : ce que l’on a appris, ce qui surprend, ce que l’on peut changer dans ses habitudes.',
                    'Exploiter le retour : activités post-visite, productions d’élèves, partage aux familles, évaluation des acquis.',
                ],
                'checklist' => [
                    'Convention de visite validée (date, durée, capacité, coût, assurance).',
                    'Ratio d’encadrement défini selon l’âge (adultes référents identifiés).',
                    'Autorisations parentales et fiches santé récupérées si nécessaire.',
                    'Consignes de sécurité distribuées avant le départ.',
                    'Transport confirmé (horaires, arrêts, plan B en cas de retard).',
                    'Objectifs pédagogiques écrits et partagés avec les participants.',
                    'Supports sur place préparés (fiches d’observation, quiz, carnet).',
                    'Activité de capitalisation post-visite planifiée.',
                ],
                'learning_objectives' => [
                    'Comprendre le cycle de production d’un aliment du champ à l’assiette.',
                    'Identifier les rôles du sol, de l’eau, de la biodiversité et du climat dans la production.',
                    'Découvrir les métiers agricoles et leurs compétences.',
                    'Distinguer production locale, saisonnalité et transformation.',
                    'Développer l’esprit critique sur les labels, l’origine et le prix des produits.',
                ],
                'recommended_program' => [
                    '00:00-00:15 — Accueil, présentation de la ferme, règles de sécurité.',
                    '00:15-00:45 — Parcours guidé : zones de production, matériel, animaux/cultures.',
                    '00:45-01:15 — Atelier pratique (tri, semis, observation du sol, alimentation animale).',
                    '01:15-01:30 — Pause et questions libres.',
                    '01:30-02:00 — Focus “de la ferme à l’assiette” + saisonnalité.',
                    '02:00-02:20 — Restitution par les participants (ce qu’ils retiennent).',
                    '02:20-02:30 — Conclusion, remerciements, rappel des prolongements pédagogiques.',
                ],
                'age_adaptations' => [
                    'Maternelle : activités sensorielles, vocabulaire simple, séquences très courtes.',
                    'Primaire : observation guidée, manipulations concrètes, schémas simples.',
                    'Secondaire : enjeux économiques/environnementaux, débats, analyse de données.',
                    'Adultes/familles : focus consommation, prix, qualité, saisonnalité et circuits de vente.',
                ],
                'pedagogical_activities' => [
                    'Atelier “reconnaître les cultures” (feuilles, graines, odeurs).',
                    'Mini-enquête “combien d’étapes avant l’assiette ?”.',
                    'Jeu de rôle “producteur-transformateur-distributeur-consommateur”.',
                    'Mesure simple de texture du sol et discussion sur fertilité/érosion.',
                    'Atelier anti-gaspillage à partir de produits de saison.',
                ],
                'risk_prevention' => [
                    'Interdiction de courir près des machines, animaux et zones techniques.',
                    'Lavage des mains obligatoire avant/après manipulations et dégustations.',
                    'Encadrement renforcé lors des déplacements en groupe.',
                    'Zone refuge en cas d’intempéries identifiée à l’avance.',
                    'Gestion des allergies et restrictions alimentaires anticipée.',
                ],
                'budget_items' => [
                    'Transport (car, covoiturage, transport public).',
                    'Forfait d’accueil/animation de la ferme.',
                    'Supports pédagogiques (impressions, carnets, matériel atelier).',
                    'Équipement complémentaire (gants, surchaussures, gel hydroalcoolique).',
                    'Marge imprévus (10 à 15 % du budget).',
                ],
                'evaluation_method' => [
                    'Questionnaire avant/après visite pour mesurer l’évolution des connaissances.',
                    'Production d’une restitution (affiche, podcast, mini-vidéo, exposé).',
                    'Auto-évaluation des participants sur les apprentissages clés.',
                    'Retour de l’exploitant sur l’implication et la qualité des échanges.',
                    'Bilan final organisateur : points forts, points d’amélioration, actions de suivi.',
                ],
            ],
            [
                'id' => 'formations-metiers',
                'title' => 'Formations et métiers',
                'description' => 'Explorer les parcours liés à l’agriculture et l’agroalimentaire.',
                'overview' => 'Panorama des métiers agricoles et agroalimentaires, des compétences attendues et des options de formation initiale ou continue.',
                'for' => 'Étudiants, personnes en reconversion, demandeurs d’emploi et conseillers orientation.',
                'steps' => [
                    'Identifier le domaine visé : production, élevage, transformation, vente, conseil, maintenance.',
                    'Comparer les parcours : enseignement secondaire qualifiant, supérieur, apprentissage, formation continue.',
                    'Réaliser une immersion (stage court, journée découverte, job étudiant).',
                    'Évaluer les compétences transversales à développer : numérique, gestion, communication, sécurité.',
                    'Construire un plan d’action sur 6 à 12 mois (formation, réseau, expériences).',
                ],
                'checklist' => [
                    'Projet métier clarifié avec au moins 2 options.',
                    'Calendrier de candidatures et stages prêt.',
                    'Budget et aides de formation vérifiés.',
                    'Premier contact avec des professionnels établi.',
                ],
            ],
            [
                'id' => 'consommation-responsable',
                'title' => 'Consommation responsable',
                'description' => 'Repères pratiques pour des achats plus durables.',
                'overview' => 'Méthode simple pour acheter mieux : saisonnalité, origine, juste prix, réduction du gaspillage et équilibre budgétaire.',
                'for' => 'Ménages, associations de consommateurs, groupes d’achat.',
                'steps' => [
                    'Planifier 4 à 6 repas avant les courses pour limiter les achats impulsifs.',
                    'Prioriser des produits de saison et d’origine locale quand c’est possible.',
                    'Comparer le prix au kilo et non seulement le prix unitaire.',
                    'Diversifier les sources d’achat : marché, vente directe, magasin de proximité.',
                    'Suivre les restes et prévoir une recette “anti-gaspi” hebdomadaire.',
                ],
                'checklist' => [
                    'Menu de la semaine préparé.',
                    'Liste de courses structurée par rayons.',
                    'Produits frais planifiés selon leur durée de conservation.',
                    'Objectif de réduction du gaspillage défini.',
                ],
            ],
            [
                'id' => 'calendrier-marches-locaux',
                'title' => 'Calendrier des marchés locaux',
                'description' => 'Repérer les marchés de producteurs et points de vente à la ferme.',
                'overview' => 'Référentiel pratique pour organiser ses achats locaux selon les jours, les saisons et les horaires des marchés.',
                'for' => 'Habitants, nouveaux arrivants, collectivités locales.',
                'steps' => [
                    'Lister les marchés hebdomadaires autour du domicile ou du lieu de travail.',
                    'Repérer les marchés saisonniers, foires agricoles et journées portes ouvertes.',
                    'Identifier les producteurs vendant en direct et leurs spécialités.',
                    'Prévoir une rotation de lieux d’achat pour lisser budget et diversité.',
                    'Partager le calendrier avec voisins, amis ou associations de quartier.',
                ],
                'checklist' => [
                    'Trois marchés de proximité identifiés.',
                    'Créneaux compatibles avec l’agenda personnel.',
                    'Contacts producteurs enregistrés.',
                    'Alternative prévue en cas d’absence d’un marché.',
                ],
            ],
            [
                'id' => 'aides-accompagnement',
                'title' => 'Aides et accompagnement',
                'description' => 'Comprendre les dispositifs d’appui à la transition agroécologique.',
                'overview' => 'Guide exhaustif pour identifier, préparer, déposer et suivre des demandes d’aides agricoles (investissement, transition, diversification, énergie, formation, accompagnement collectif), avec une logique pas-à-pas.',
                'for' => 'Agriculteurs en activité, jeunes installés, porteurs de projet, CUMA, coopératives, collectivités, structures de conseil et associations rurales.',
                'steps' => [
                    'Étape 1 — Clarifier le besoin : définir précisément le projet (modernisation, conversion, diversification, irrigation, sobriété énergétique, transformation à la ferme, etc.).',
                    'Étape 2 — Diagnostiquer le point de départ : établir un état initial (technique, économique, environnemental, social) avec des indicateurs mesurables.',
                    'Étape 3 — Cartographier les guichets : lister les financeurs et accompagnateurs possibles (région, commune, intercommunale, organismes professionnels, dispositifs européens, appels à projets).',
                    'Étape 4 — Vérifier l’éligibilité : comparer les critères du dispositif (profil du demandeur, taille de l’exploitation, zone géographique, nature des dépenses, délais).',
                    'Étape 5 — Construire le plan d’investissement : détailler postes de dépenses, devis, calendrier de réalisation et modalités de financement complémentaires.',
                    'Étape 6 — Préparer les pièces administratives : identité juridique, attestations, données économiques, éléments fonciers, preuves de conformité réglementaire.',
                    'Étape 7 — Formaliser les impacts attendus : gains de performance, réduction des consommations, amélioration de revenu, effets sur biodiversité/eau/sol/climat.',
                    'Étape 8 — Déposer la demande dans les délais : vérifier signatures, annexes, format attendu et accusé de réception.',
                    'Étape 9 — Sécuriser la mise en œuvre : lancer les dépenses uniquement selon les règles du dispositif et archiver toutes les preuves.',
                    'Étape 10 — Assurer le suivi et le reporting : documenter l’avancement, transmettre les justificatifs, préparer les contrôles et l’évaluation finale.',
                ],
                'checklist' => [
                    'Objectif principal du projet formulé en une phrase claire.',
                    'Budget prévisionnel complet (HT/TTC) avec devis datés et comparables.',
                    'Plan de financement équilibré (aides, emprunt, autofinancement, trésorerie).',
                    'Critères d’éligibilité validés point par point.',
                    'Dossier administratif complet et relu avant dépôt.',
                    'Calendrier des jalons (dépôt, instruction, décision, démarrage, clôture) validé.',
                    'Procédure d’archivage des pièces (numérique + papier) en place.',
                    'Indicateurs de résultats définis avant démarrage.',
                    'Référent technique/administratif identifié dans l’équipe ou l’accompagnement.',
                    'Plan de gestion des risques (retard travaux, surcoûts, refus partiel, contrôle) préparé.',
                ],
                'eligible_projects' => [
                    'Investissements de modernisation (matériel, bâtiments, sécurité, ergonomie).',
                    'Transition agroécologique (sols, biodiversité, intrants, eau, autonomie fourragère).',
                    'Performance énergétique (isolation, efficacité, production d’énergie renouvelable).',
                    'Diversification et transformation (ateliers de transformation, vente directe, nouveaux débouchés).',
                    'Innovation et numérique (outils d’aide à la décision, capteurs, traçabilité).',
                    'Actions collectives (mutualisation, coopération territoriale, formations de groupe).',
                ],
                'required_documents' => [
                    'Pièce d’identité et statuts/forme juridique de la structure.',
                    'Numéros administratifs de l’exploitation et attestations à jour.',
                    'Bilans/comptes de résultat récents ou prévisionnels pour les porteurs de projet.',
                    'Devis détaillés, plans, descriptifs techniques et calendrier des travaux.',
                    'Justificatifs fonciers (propriété, bail, autorisations) selon le projet.',
                    'Attestations de conformité réglementaire (urbanisme, environnement, sécurité).',
                    'Note de motivation précisant objectifs, impacts et cohérence territoriale.',
                ],
                'timeline' => [
                    'Semaine 1-2 : cadrage du besoin et collecte d’informations.',
                    'Semaine 3-6 : montage technique et financier du dossier.',
                    'Semaine 7-8 : relecture externe et dépôt.',
                    'Mois 3-6 : phase d’instruction et éventuelles demandes de compléments.',
                    'Après accord : lancement opérationnel, suivi des dépenses et reporting.',
                ],
                'common_pitfalls' => [
                    'Dépenses engagées avant l’accord, rendant certaines lignes inéligibles.',
                    'Dossier incomplet ou non conforme au format demandé.',
                    'Objectifs trop vagues, sans indicateurs mesurables.',
                    'Sous-estimation des délais administratifs et techniques.',
                    'Absence de plan de trésorerie pour absorber les avances de dépenses.',
                ],
                'support_contacts' => [
                    'Guichets agricoles régionaux : orientation sur les appels ouverts et l’éligibilité.',
                    'Centres de gestion et conseillers technico-économiques : sécurisation du business plan.',
                    'Structures locales de développement rural : articulation avec les projets de territoire.',
                    'Réseaux professionnels agricoles : retours d’expérience et mutualisation des bonnes pratiques.',
                ],
            ],
            [
                'id' => 'decouvrir-labels',
                'title' => 'Découvrir les labels',
                'description' => 'Comparer les principaux labels qualité, origine et durabilité.',
                'overview' => 'Clés de lecture pour comprendre les labels alimentaires et éviter les confusions entre origine, qualité sanitaire et impact environnemental.',
                'for' => 'Consommateurs, animateurs d’ateliers, structures éducatives.',
                'steps' => [
                    'Identifier la promesse du label : origine, méthode de production, cahier des charges.',
                    'Vérifier la présence d’un organisme de contrôle indépendant.',
                    'Comparer plusieurs produits d’une même catégorie avec les mêmes critères.',
                    'Repérer les mentions marketing non certifiées pour éviter les biais.',
                    'Conserver une logique d’ensemble : label + saison + proximité + budget.',
                ],
                'checklist' => [
                    'Au moins trois labels compris et comparés.',
                    'Différence entre certification et argument marketing maîtrisée.',
                    'Critères personnels de choix formalisés.',
                    'Habitude d’achat alignée avec ces critères.',
                ],
            ],
            [
                'id' => 'boite-a-outils-anti-gaspillage',
                'title' => 'Boîte à outils anti-gaspillage',
                'description' => 'Astuces pour mieux conserver, cuisiner et valoriser les produits frais.',
                'overview' => 'Boîte à outils opérationnelle pour réduire les pertes alimentaires à la maison et mieux valoriser chaque produit.',
                'for' => 'Familles, étudiants, cuisines collectives, associations.',
                'steps' => [
                    'Classer les aliments selon leur sensibilité (très périssable, moyen, longue conservation).',
                    'Adopter la règle FIFO (premier entré, premier sorti) dans le frigo et les placards.',
                    'Programmer une “recette de récupération” hebdomadaire.',
                    'Congeler intelligemment avec portions, dates et étiquettes.',
                    'Composter les biodéchets non consommables quand c’est possible.',
                ],
                'checklist' => [
                    'Inventaire hebdomadaire du frigo réalisé.',
                    'Restes valorisés au moins une fois par semaine.',
                    'Plan de conservation affiché en cuisine.',
                    'Volume de déchets alimentaires suivi mensuellement.',
                ],
            ],
            [
                'id' => 'parcours-pedagogiques',
                'title' => 'Parcours pédagogiques',
                'description' => 'Ressources pour enseignants et familles autour de l’alimentation et des saisons.',
                'overview' => 'Parcours d’apprentissage progressifs (primaire, secondaire, famille) autour de l’alimentation, des saisons et des métiers agricoles.',
                'for' => 'Enseignants, éducateurs, parents et médiateurs scientifiques.',
                'steps' => [
                    'Choisir un niveau (débutant, intermédiaire, avancé) selon l’âge des participants.',
                    'Structurer le parcours en séquences courtes : comprendre, observer, pratiquer, restituer.',
                    'Combiner supports : vidéos courtes, fiches, expériences simples et sortie terrain.',
                    'Évaluer les acquis avec un mini-projet (affiche, capsule audio, quiz).',
                    'Capitaliser les résultats pour réutilisation l’année suivante.',
                ],
                'checklist' => [
                    'Objectifs pédagogiques explicités.',
                    'Supports et activités adaptés à l’âge.',
                    'Moment de restitution prévu.',
                    'Évaluation finale simple préparée.',
                ],
            ],
        ],
    ];
}
