<?php

declare(strict_types=1);

/**
 * @return array<string, mixed>
 */
function getPortalData(): array
{
    return [
        'site' => [
            'title' => 'MyAgri — Portail citoyen',
            'subtitle' => 'Comprendre l’agriculture wallonne : alimentation, territoires, environnement, économie et métiers.',
            'updated_at' => '25 avril 2026',
        ],
        'quickFacts' => [
            [
                'title' => 'Un enjeu quotidien',
                'content' => 'L’agriculture influence directement le prix, la qualité et la diversité de notre alimentation.',
            ],
            [
                'title' => 'Un rôle territorial',
                'content' => 'Elle structure les paysages, soutient l’emploi local et maintient la vie économique rurale.',
            ],
            [
                'title' => 'Un secteur en transition',
                'content' => 'Les fermes s’adaptent au climat, à la pression économique et aux attentes sociétales.',
            ],
            [
                'title' => 'Un moteur d’innovation',
                'content' => 'Du numérique aux nouvelles variétés, les pratiques évoluent pour produire mieux avec moins de ressources.',
            ],
            [
                'title' => 'Un lien social',
                'content' => 'Marchés, coopératives, fermes pédagogiques et circuits courts rapprochent citoyens et producteurs.',
            ],
        ],
        'pillars' => [
            ['name' => 'Produire', 'description' => 'Assurer une production fiable, diversifiée et de qualité pour répondre aux besoins alimentaires.'],
            ['name' => 'Préserver', 'description' => 'Protéger l’eau, les sols, le climat et la biodiversité pour maintenir la capacité de production sur le long terme.'],
            ['name' => 'Relier', 'description' => 'Créer du lien entre producteurs, transformateurs, distributeurs et citoyens via des filières lisibles.'],
            ['name' => 'Innover', 'description' => 'S’appuyer sur la recherche, l’expérimentation et les retours terrain pour améliorer les pratiques.'],
        ],
        'sectors' => [
            [
                'label' => 'Grandes cultures',
                'emoji' => '🌾',
                'summary' => 'Céréales, pommes de terre et betteraves occupent une place importante.',
                'enjeux' => [
                    'Gestion des risques climatiques.',
                    'Fertilité des sols et rotations.',
                    'Stabilité économique des exploitations.',
                    'Disponibilité de l’eau et maîtrise des intrants.',
                ],
                'public_actions' => [
                    'Privilégier la saisonnalité et l’origine locale.',
                    'S’informer sur les filières de transformation régionales.',
                    'Réduire le gaspillage alimentaire pour valoriser au mieux le travail agricole.',
                ],
            ],
            [
                'label' => 'Élevage bovin et laitier',
                'emoji' => '🐄',
                'summary' => 'L’élevage valorise les prairies et alimente les filières laitières et viandeuses.',
                'enjeux' => [
                    'Bien-être animal et revenu des éleveurs.',
                    'Autonomie fourragère et coûts de production.',
                    'Réduction de l’empreinte environnementale.',
                    'Transmission des fermes et renouvellement des générations.',
                ],
                'public_actions' => [
                    'Découvrir les labels et démarches qualité.',
                    'Soutenir les points de vente fermiers.',
                    'Comparer l’origine des produits laitiers et carnés pour encourager les filières locales.',
                ],
            ],
            [
                'label' => 'Maraîchage, horticulture et vergers',
                'emoji' => '🥕',
                'summary' => 'Des productions de proximité adaptées aux circuits courts.',
                'enjeux' => [
                    'Main-d’œuvre, stockage et logistique.',
                    'Irrigation et adaptation aux canicules.',
                    'Valorisation commerciale en vente directe.',
                    'Accès au foncier de proximité pour de nouveaux maraîchers.',
                ],
                'public_actions' => [
                    'Acheter en direct chez les producteurs.',
                    'Diversifier son panier avec des produits de saison.',
                    'Planifier ses menus hebdomadaires pour soutenir une consommation locale régulière.',
                ],
            ],
            [
                'label' => 'Diversification (petits fruits, houblon, viticulture)',
                'emoji' => '🍇',
                'summary' => 'Des filières émergentes créent de la valeur locale et renforcent la résilience des fermes.',
                'enjeux' => [
                    'Investissements de départ et accompagnement technique.',
                    'Structuration des débouchés locaux et touristiques.',
                    'Gestion des risques sanitaires et climatiques.',
                    'Développement de compétences en transformation et commercialisation.',
                ],
                'public_actions' => [
                    'Découvrir les produits locaux transformés (jus, bière, vin, confitures).',
                    'Visiter les exploitations qui ouvrent leurs ateliers au public.',
                    'Choisir des cadeaux alimentaires issus de producteurs régionaux.',
                ],
            ],
        ],
        'focusThemes' => [
            ['title' => 'Eau', 'details' => 'Économiser et mieux stocker l’eau pour sécuriser les productions.'],
            ['title' => 'Sols', 'details' => 'Renforcer la matière organique et limiter l’érosion.'],
            ['title' => 'Biodiversité', 'details' => 'Déployer haies, bandes fleuries et infrastructures écologiques.'],
            ['title' => 'Climat', 'details' => 'Adapter les pratiques et limiter les émissions.'],
            ['title' => 'Énergie', 'details' => 'Réduire les coûts via l’efficacité énergétique et l’autoproduction.'],
            ['title' => 'Numérique', 'details' => 'Mieux piloter les cultures et troupeaux grâce aux données de terrain.'],
        ],

        'provinces' => [
            ['name' => 'Brabant wallon', 'profile' => 'Mosaïque de cultures, maraîchage et transformation locale, avec une forte proximité des bassins de consommation.'],
            ['name' => 'Hainaut', 'profile' => 'Poids important des grandes cultures et de l’agroalimentaire, soutenu par des infrastructures logistiques structurantes.'],
            ['name' => 'Liège', 'profile' => 'Élevage, vergers et filières de valorisation de proximité, avec des initiatives dynamiques en circuits courts.'],
            ['name' => 'Luxembourg', 'profile' => 'Systèmes herbagers, forêts et élevage extensif, dans des paysages où l’équilibre entre production et nature est central.'],
            ['name' => 'Namur', 'profile' => 'Diversité de productions entre grandes cultures, élevage et maraîchage, avec un tissu d’exploitations familiales varié.'],
        ],
        'seasonalCalendar' => [
            ['season' => 'Printemps', 'focus' => 'Semis, gestion de l’eau, protection contre le gel tardif et organisation des premières récoltes.'],
            ['season' => 'Été', 'focus' => 'Récoltes précoces, irrigation ciblée, prévention du stress hydrique et gestion des pics de travail.'],
            ['season' => 'Automne', 'focus' => 'Récoltes principales, semis d’automne, couverts végétaux et préparation des sols pour l’hiver.'],
            ['season' => 'Hiver', 'focus' => 'Entretien du matériel, planification, soins aux animaux et préparation de la campagne suivante.'],
        ],
        'faq' => [
            [
                'q' => 'Pourquoi les prix agricoles sont-ils parfois instables ?',
                'a' => 'Ils dépendent à la fois des marchés mondiaux, de la météo, des coûts de l’énergie et de la transformation.',
            ],
            [
                'q' => 'Le circuit court est-il toujours possible ?',
                'a' => 'Pas pour tous les produits, mais il peut renforcer le lien local et la valeur ajoutée quand il est bien organisé.',
            ],
            [
                'q' => 'Comment sensibiliser les enfants ?',
                'a' => 'Via des visites de fermes, des ateliers alimentaires, des potagers et l’observation des saisons.',
            ],
            [
                'q' => 'Pourquoi parle-t-on autant de souveraineté alimentaire ?',
                'a' => 'Elle vise à garantir une capacité locale à produire une part significative de l’alimentation en cas de crise.',
            ],
            [
                'q' => 'Que signifie “prix juste” pour un agriculteur ?',
                'a' => 'Un prix qui couvre les coûts de production, rémunère le travail et permet d’investir dans la transition.',
            ],
            [
                'q' => 'Comment un citoyen peut-il agir sans augmenter fortement son budget ?',
                'a' => 'En privilégiant la saison, en cuisinant des produits bruts, en limitant le gaspillage et en comparant les points de vente locaux.',
            ],
            [
                'q' => 'Pourquoi les pratiques agricoles varient-elles d’une région à l’autre ?',
                'a' => 'Les choix techniques dépendent du climat, des sols, du relief, des filières présentes et des débouchés économiques locaux.',
            ],
        ],
        'glossary' => [
            ['term' => 'Agroécologie', 'definition' => 'Application de principes écologiques à la production agricole.'],
            ['term' => 'Rotation', 'definition' => 'Alternance planifiée des cultures sur une même parcelle.'],
            ['term' => 'Circuit court', 'definition' => 'Vente avec peu ou pas d’intermédiaires.'],
            ['term' => 'Prairie permanente', 'definition' => 'Prairie installée durablement, utile à l’élevage et aux écosystèmes.'],
            ['term' => 'Autonomie fourragère', 'definition' => 'Capacité d’un élevage à produire la majorité de l’alimentation de ses animaux.'],
            ['term' => 'Couvert végétal', 'definition' => 'Culture implantée entre deux cultures principales pour protéger et enrichir le sol.'],
            ['term' => 'Assolement', 'definition' => 'Répartition des différentes cultures sur les parcelles d’une exploitation pour une campagne donnée.'],
            ['term' => 'Intrants', 'definition' => 'Ensemble des produits utilisés pour produire : semences, engrais, produits de protection, énergie, aliments du bétail, etc.'],
            ['term' => 'Polyculture-élevage', 'definition' => 'Système qui combine cultures et élevage sur la même ferme pour mieux valoriser les ressources.'],
            ['term' => 'Résilience', 'definition' => 'Capacité d’une exploitation à absorber un choc (climat, prix, crise sanitaire) et à continuer de fonctionner.'],
            ['term' => 'Traçabilité', 'definition' => 'Possibilité de suivre un produit de son origine à sa vente grâce à des informations vérifiables.'],
            ['term' => 'Bilan carbone', 'definition' => 'Évaluation des émissions de gaz à effet de serre générées par une activité ou une filière.'],
            ['term' => 'Haie vive', 'definition' => 'Alignement d’arbustes et d’arbres jouant un rôle pour la biodiversité, le vent, l’eau et les paysages.'],
            ['term' => 'Filière', 'definition' => 'Chaîne d’acteurs allant de la production à la transformation puis à la distribution d’un produit agricole.'],
            ['term' => 'Valeur ajoutée', 'definition' => 'Richesse créée par la transformation, la qualité, l’origine ou le mode de commercialisation d’un produit.'],
            ['term' => 'Agriculture de précision', 'definition' => 'Utilisation d’outils numériques (capteurs, GPS, données) pour ajuster les pratiques au plus juste.'],
            ['term' => 'Agriculture biologique', 'definition' => 'Mode de production reposant sur des règles spécifiques limitant les intrants de synthèse et favorisant les équilibres naturels.'],
            ['term' => 'Agroforesterie', 'definition' => 'Association d’arbres et de cultures ou d’élevage sur une même parcelle pour renforcer les services écosystémiques.'],
            ['term' => 'AOP/IGP', 'definition' => 'Signes officiels de qualité liés à l’origine géographique et à un savoir-faire reconnu.'],
            ['term' => 'Bocage', 'definition' => 'Paysage agricole composé de parcelles entourées de haies, favorable à la biodiversité et à la protection des sols.'],
            ['term' => 'Couverts permanents', 'definition' => 'Présence continue de végétation sur le sol afin de réduire l’érosion et améliorer sa structure.'],
            ['term' => 'Cultures associées', 'definition' => 'Conduite simultanée de plusieurs espèces sur une même parcelle pour mieux utiliser les ressources.'],
            ['term' => 'Densité de chargement', 'definition' => 'Nombre d’animaux rapporté à une surface donnée, indicateur de pression sur les prairies et ressources.'],
            ['term' => 'Diversification', 'definition' => 'Ajout de nouvelles productions, activités ou circuits de vente pour sécuriser les revenus de la ferme.'],
            ['term' => 'Économie circulaire', 'definition' => 'Organisation visant à réduire les pertes de matière et d’énergie en favorisant réemploi, recyclage et valorisation locale.'],
            ['term' => 'Élevage extensif', 'definition' => 'Système d’élevage basé sur une faible densité animale et une forte valorisation des surfaces herbagères.'],
            ['term' => 'Érosion des sols', 'definition' => 'Perte de particules de sol sous l’action de l’eau ou du vent, pouvant réduire la fertilité des parcelles.'],
            ['term' => 'Fertilité du sol', 'definition' => 'Capacité d’un sol à fournir eau, nutriments et conditions favorables à la croissance des cultures.'],
            ['term' => 'Gestion intégrée des ravageurs', 'definition' => 'Approche combinant prévention, observation et interventions ciblées pour limiter les dégâts sanitaires.'],
            ['term' => 'Humus', 'definition' => 'Fraction organique stable du sol contribuant à sa structure, sa fertilité et sa capacité de rétention d’eau.'],
            ['term' => 'Irrigation raisonnée', 'definition' => 'Apport d’eau ajusté aux besoins réels des cultures pour optimiser la ressource et éviter les excès.'],
            ['term' => 'Matière organique', 'definition' => 'Ensemble des résidus végétaux et animaux en décomposition qui nourrissent la vie du sol.'],
            ['term' => 'Méthanisation', 'definition' => 'Processus biologique transformant des matières organiques en biogaz et digestat valorisable en agriculture.'],
            ['term' => 'PAC', 'definition' => 'Politique Agricole Commune de l’Union européenne, cadre d’aides, de règles et d’orientations pour l’agriculture.'],
            ['term' => 'Pâturage tournant', 'definition' => 'Méthode de gestion des prairies qui alterne les parcelles pâturées afin d’améliorer la repousse de l’herbe.'],
            ['term' => 'Pertes post-récolte', 'definition' => 'Quantités perdues entre la récolte et la consommation à cause du stockage, du transport ou de la transformation.'],
            ['term' => 'Plan de fumure', 'definition' => 'Programmation des apports fertilisants selon les besoins des cultures et les caractéristiques des sols.'],
            ['term' => 'Prix rémunérateur', 'definition' => 'Prix permettant de couvrir les coûts de production et d’assurer un revenu viable à l’exploitant.'],
            ['term' => 'Protéagineux', 'definition' => 'Cultures riches en protéines (pois, féverole, lupin, etc.) utilisées en alimentation humaine ou animale.'],
            ['term' => 'Saisonnalité', 'definition' => 'Période naturelle de production d’un aliment, influençant disponibilité, goût, coût et impact environnemental.'],
            ['term' => 'Séquestration carbone', 'definition' => 'Stockage du carbone dans les sols et la biomasse, contribuant à atténuer le changement climatique.'],
            ['term' => 'Souveraineté alimentaire', 'definition' => 'Capacité d’un territoire à organiser durablement son alimentation et à sécuriser son approvisionnement.'],
            ['term' => 'Stress hydrique', 'definition' => 'Situation où les besoins en eau des cultures dépassent les disponibilités, affectant rendement et qualité.'],
            ['term' => 'Transformation à la ferme', 'definition' => 'Valorisation des productions directement sur l’exploitation (fromage, jus, yaourt, etc.).'],
            ['term' => 'Transition agroécologique', 'definition' => 'Évolution progressive des systèmes agricoles vers des pratiques plus durables sur les plans environnemental, social et économique.'],
            ['term' => 'Zéro artificialisation nette (ZAN)', 'definition' => 'Objectif visant à limiter la consommation d’espaces naturels, agricoles et forestiers par l’urbanisation.'],
        ],
        'resources' => [
            [
                'id' => 'visites-pedagogiques',
                'title' => 'Visites pédagogiques',
                'description' => 'Trouver des fermes ouvertes au public et aux écoles.',
                'overview' => 'Guide exhaustif pour concevoir, animer et évaluer une visite pédagogique agricole : objectifs d’apprentissage, sécurité, déroulé minute par minute, activités selon l’âge, budget, communication et exploitation pédagogique après la sortie.',
                'for' => 'Écoles maternelles/primaires/secondaires, associations jeunesse, maisons de quartier, centres culturels, familles, animateurs nature et collectivités.',
                'continuous_content' => 'Cette ressource propose un cadre complet pour organiser une visite pédagogique en ferme, depuis la définition des objectifs d’apprentissage jusqu’au bilan final avec les participants. Elle aide à choisir un lieu adapté, à préparer les règles de sécurité, à planifier les séquences d’animation et à prévoir la logistique, afin que la sortie soit à la fois formatrice, sécurisée et engageante. Le contenu insiste sur la pédagogie active, l’observation du terrain, la compréhension du lien entre production et alimentation, ainsi que sur l’exploitation après visite à travers des activités de restitution, des productions d’élèves et un partage avec les familles. En pratique, cette page sert de fil conducteur pour transformer une simple découverte de ferme en véritable projet éducatif structuré.',
                'steps' => [
                    'Cadrer les objectifs pédagogiques : alimentation, saisonnalité, biodiversité, bien-être animal, métiers, climat, eau, sol, circuits courts.',
                    'Sélectionner une ferme adaptée au public (accessibilité, capacité d’accueil, infrastructures sanitaires, zones couvertes, assurance).',
                    'Co-construire le scénario de visite avec l’exploitant : séquences, temps d’échange, manipulations, dégustation éventuelle.',
                    'Préparer les participants : notions clés, règles de sécurité, attentes comportementales, vêtements adaptés, questions à poser.',
                    'Valider la logistique complète : transport, timing, encadrement adulte/enfants, contacts d’urgence, trousse de secours.',
                    'Animer la visite avec pédagogie active : observation, manipulation, prise de notes, photos/documentation, restitution orale.',
                    'Conclure par une synthèse : ce que l’on a appris, ce qui surprend, ce que l’on peut changer dans ses habitudes.',
                    'Exploiter le retour : activités post-visite, productions d’élèves, partage aux familles, évaluation des acquis.',
                ],
                'checklist' => [
                    'Convention de visite validée (date, durée, capacité, coût, assurance).',
                    'Ratio d’encadrement défini selon l’âge (adultes référents identifiés).',
                    'Autorisations parentales et fiches santé récupérées si nécessaire.',
                    'Consignes de sécurité distribuées avant le départ.',
                    'Transport confirmé (horaires, arrêts, plan B en cas de retard).',
                    'Objectifs pédagogiques écrits et partagés avec les participants.',
                    'Supports sur place préparés (fiches d’observation, quiz, carnet).',
                    'Activité de capitalisation post-visite planifiée.',
                ],
                'learning_objectives' => [
                    'Comprendre le cycle de production d’un aliment du champ à l’assiette.',
                    'Identifier les rôles du sol, de l’eau, de la biodiversité et du climat dans la production.',
                    'Découvrir les métiers agricoles et leurs compétences.',
                    'Distinguer production locale, saisonnalité et transformation.',
                    'Développer l’esprit critique sur les labels, l’origine et le prix des produits.',
                ],
                'recommended_program' => [
                    '00:00-00:15 — Accueil, présentation de la ferme, règles de sécurité.',
                    '00:15-00:45 — Parcours guidé : zones de production, matériel, animaux/cultures.',
                    '00:45-01:15 — Atelier pratique (tri, semis, observation du sol, alimentation animale).',
                    '01:15-01:30 — Pause et questions libres.',
                    '01:30-02:00 — Focus “de la ferme à l’assiette” + saisonnalité.',
                    '02:00-02:20 — Restitution par les participants (ce qu’ils retiennent).',
                    '02:20-02:30 — Conclusion, remerciements, rappel des prolongements pédagogiques.',
                ],
                'age_adaptations' => [
                    'Maternelle : activités sensorielles, vocabulaire simple, séquences très courtes.',
                    'Primaire : observation guidée, manipulations concrètes, schémas simples.',
                    'Secondaire : enjeux économiques/environnementaux, débats, analyse de données.',
                    'Adultes/familles : focus consommation, prix, qualité, saisonnalité et circuits de vente.',
                ],
                'pedagogical_activities' => [
                    'Atelier “reconnaître les cultures” (feuilles, graines, odeurs).',
                    'Mini-enquête “combien d’étapes avant l’assiette ?”.',
                    'Jeu de rôle “producteur-transformateur-distributeur-consommateur”.',
                    'Mesure simple de texture du sol et discussion sur fertilité/érosion.',
                    'Atelier anti-gaspillage à partir de produits de saison.',
                ],
                'risk_prevention' => [
                    'Interdiction de courir près des machines, animaux et zones techniques.',
                    'Lavage des mains obligatoire avant/après manipulations et dégustations.',
                    'Encadrement renforcé lors des déplacements en groupe.',
                    'Zone refuge en cas d’intempéries identifiée à l’avance.',
                    'Gestion des allergies et restrictions alimentaires anticipée.',
                ],
                'budget_items' => [
                    'Transport (car, covoiturage, transport public).',
                    'Forfait d’accueil/animation de la ferme.',
                    'Supports pédagogiques (impressions, carnets, matériel atelier).',
                    'Équipement complémentaire (gants, surchaussures, gel hydroalcoolique).',
                    'Marge imprévus (10 à 15 % du budget).',
                ],
                'evaluation_method' => [
                    'Questionnaire avant/après visite pour mesurer l’évolution des connaissances.',
                    'Production d’une restitution (affiche, podcast, mini-vidéo, exposé).',
                    'Auto-évaluation des participants sur les apprentissages clés.',
                    'Retour de l’exploitant sur l’implication et la qualité des échanges.',
                    'Bilan final organisateur : points forts, points d’amélioration, actions de suivi.',
                ],
            ],
            [
                'id' => 'formations-metiers',
                'title' => 'Formations et métiers',
                'description' => 'Explorer les parcours liés à l’agriculture et l’agroalimentaire.',
                'overview' => 'Guide exhaustif d’orientation vers les métiers agricoles et agroalimentaires : familles de métiers, voies de formation, compétences, certifications, financements, stratégie de candidature et plan d’action de reconversion.',
                'for' => 'Collégiens/lycéens, étudiants, adultes en reconversion, demandeurs d’emploi, enseignants, conseillers en orientation et structures d’insertion.',
                'continuous_content' => 'La page Formations et métiers a été développée pour servir de guide d’orientation complet, depuis la première question « quel métier me correspond ? » jusqu’à la mise en action concrète sur les 90 premiers jours. Elle aide d’abord à clarifier une cible professionnelle réaliste en agriculture ou agroalimentaire (production, élevage, transformation, conseil, logistique, commercialisation), puis à comparer les parcours d’accès possibles selon le profil : formation initiale, alternance, reconversion adulte, certification courte ou validation d’acquis. Le contenu insiste sur l’importance d’un diagnostic personnel précis — compétences déjà maîtrisées, contraintes de mobilité, disponibilité, budget, rythme d’apprentissage — afin d’éviter les candidatures dispersées et de choisir une trajectoire cohérente avec les débouchés locaux. La ressource détaille ensuite la méthode la plus efficace pour passer à l’action : immersion terrain, adaptation du CV aux attendus du secteur, préparation d’exemples concrets pour l’entretien, identification des aides financières et planification d’un calendrier de candidatures. Elle met aussi en perspective les évolutions de carrière possibles, les facteurs qui influencent la rémunération et les compétences transversales qui augmentent l’employabilité durable (organisation, communication, pilotage économique, outils numériques et conformité réglementaire). L’objectif final est de transformer une intention d’orientation en plan opérationnel mesurable, avec des étapes réalistes, des preuves d’avancement et une meilleure sécurisation de l’entrée dans le métier.',
                'steps' => [
                    'Étape 1 — Définir un cap métier : production végétale, élevage, transformation, commercialisation, conseil, maintenance, logistique ou qualité.',
                    'Étape 2 — Évaluer son profil : acquis scolaires/professionnels, contraintes géographiques, disponibilité, budget, rythme d’apprentissage.',
                    'Étape 3 — Identifier les parcours adaptés : formation initiale, alternance, apprentissage, formation continue, VAE.',
                    'Étape 4 — Vérifier les prérequis et débouchés : niveau d’entrée, compétences attendues, taux d’insertion, mobilité requise.',
                    'Étape 5 — Réaliser une immersion terrain : stage d’observation, PMSMP, visite d’entreprise, journée d’essai.',
                    'Étape 6 — Construire son dossier : CV orienté compétences, lettre de motivation ciblée, portfolio/projet professionnel.',
                    'Étape 7 — Mobiliser les financements : aides publiques, dispositifs régionaux, financement employeur, bourses, alternance.',
                    'Étape 8 — Mettre en œuvre un plan d’évolution sur 6 à 12 mois avec jalons mensuels.',
                ],
                'checklist' => [
                    'Projet métier clarifié avec 2 à 3 pistes réalistes.',
                    'Compétences déjà maîtrisées vs compétences à acquérir documentées.',
                    'Parcours de formation comparés avec critères objectifs.',
                    'Calendrier de candidatures/stages/concours établi.',
                    'Solution de financement identifiée et vérifiée.',
                    'Réseau professionnel initial constitué (contacts terrain).',
                    'Premier pas concret planifié dans les 30 jours.',
                ],
                'job_families' => [
                    'Production végétale : grandes cultures, maraîchage, arboriculture, horticulture.',
                    'Élevage : bovin lait/viande, ovins, caprins, aviculture, bien-être animal.',
                    'Transformation agroalimentaire : fromagerie, boulangerie, conserverie, boissons.',
                    'Commercialisation : circuits courts, vente directe, logistique, distribution spécialisée.',
                    'Appui technique : conseil agronomique, expérimentation, agroéquipement, qualité.',
                    'Fonctions transversales : gestion, achats, marketing territorial, RSE, traçabilité.',
                ],
                'training_paths' => [
                    'Secondaire qualifiant agricole et agroalimentaire.',
                    'BTS/Bachelor/Licence professionnelle en agronomie, agroéquipement, qualité, commerce.',
                    'Écoles d’ingénieurs/agronomie pour les profils conception/management.',
                    'Apprentissage/alternance pour accélérer l’employabilité.',
                    'Formation continue courte (certificats techniques, hygiène, sécurité, conduite).',
                    'Validation des acquis de l’expérience (VAE) pour formaliser l’expérience terrain.',
                ],
                'key_skills' => [
                    'Compétences techniques : conduite culturale/élevage, transformation, maintenance de base.',
                    'Compétences numériques : outils de suivi, traçabilité, saisie de données, reporting.',
                    'Compétences économiques : calcul de coûts, marge, prix de revient, pilotage d’activité.',
                    'Compétences humaines : organisation, communication, travail d’équipe, relation client.',
                    'Compétences réglementaires : sécurité, hygiène, environnement, bien-être animal.',
                ],
                'certifications' => [
                    'Hygiène et sécurité alimentaire (HACCP et pratiques associées).',
                    'Certificats de conduite d’engins et sécurité au travail.',
                    'Certifications qualité/environnement selon les filières.',
                    'Modules courts spécialisés : irrigation, taille, fromagerie, commercialisation directe.',
                ],
                'financing_options' => [
                    'Contrat d’alternance ou d’apprentissage (cofinancement employeur/organisme).',
                    'Aides publiques régionales et dispositifs de reconversion.',
                    'Financements via opérateurs de compétences / employeur.',
                    'Bourses, aides mobilité et aides sociales selon situation personnelle.',
                ],
                'application_tips' => [
                    'Adapter le CV au poste visé avec preuves concrètes (stages, projets, réalisations).',
                    'Valoriser les compétences transférables issues d’autres secteurs.',
                    'Préparer 3 exemples terrain pour l’entretien (problème, action, résultat).',
                    'Montrer sa connaissance des enjeux agricoles actuels (climat, coûts, qualité, marché).',
                ],
                'salary_factors' => [
                    'Niveau de qualification et degré d’autonomie sur le poste.',
                    'Type d’entreprise (exploitation, coopérative, industrie, distribution).',
                    'Localisation géographique et tension sur les profils.',
                    'Horaires spécifiques, saisonnalité et polyvalence demandée.',
                ],
                'mobility_paths' => [
                    'Technicien -> chef d’équipe -> responsable d’atelier.',
                    'Vente directe -> gestion commerciale -> développement de filière.',
                    'Production -> transformation -> qualité/traçabilité.',
                    'Exploitation -> conseil technique -> formation/accompagnement.',
                ],
                'action_plan_90_days' => [
                    'Jours 1-15 : diagnostic personnel, choix de 2 métiers cibles et 5 contacts terrain.',
                    'Jours 16-30 : immersion courte + adaptation CV/lettre + repérage formations.',
                    'Jours 31-60 : candidatures ciblées, entretiens, recherche de financement.',
                    'Jours 61-90 : démarrage formation ou prise de poste/stage avec objectifs mesurables.',
                ],
            ],
            [
                'id' => 'consommation-responsable',
                'title' => 'Consommation responsable',
                'description' => 'Repères pratiques pour des achats plus durables.',
                'overview' => 'Guide exhaustif pour acheter, cuisiner et consommer de manière responsable en conciliant budget, santé, impact environnemental, soutien aux producteurs locaux et réduction du gaspillage.',
                'for' => 'Ménages, étudiants, familles, associations de consommateurs, groupes d’achat, collectivités et structures d’éducation à l’alimentation.',
                'continuous_content' => 'Cette page est développée comme un guide exhaustif de consommation responsable, pensé pour accompagner un foyer du diagnostic initial jusqu’à une amélioration durable de ses pratiques alimentaires sur plusieurs mois. Elle commence par une étape d’observation concrète, en invitant à analyser les tickets de caisse, le contenu des poubelles alimentaires, la fréquence des achats impulsifs et la part de produits ultra-transformés, afin d’établir une photographie réaliste des habitudes existantes. À partir de ce point de départ, la ressource propose de fixer des objectifs mesurables et progressifs, par exemple un budget hebdomadaire cible, une part minimale de produits de saison, un niveau de réduction du gaspillage ou une amélioration du coût moyen par repas, pour transformer la bonne intention en pilotage concret. Le cœur de la méthode repose ensuite sur la planification : organiser les menus de la semaine, anticiper les contraintes d’horaires, prévoir des alternatives selon les promotions ou disponibilités locales, préparer une liste de courses hiérarchisée et calibrer les quantités à la consommation réelle du foyer pour éviter les surplus. La page détaille également une stratégie d’achat opérationnelle qui combine comparaison des prix au kilo, lecture attentive des étiquettes, arbitrage entre origine, labels et niveau de transformation, et diversification des points d’approvisionnement entre marchés, vente directe, coopératives et commerce de proximité, afin de trouver le meilleur équilibre entre qualité, impact et accessibilité économique. Une section importante est consacrée à la conservation et à la cuisine d’optimisation, avec des principes de batch cooking, de gestion des portions, d’étiquetage des restes, de congélation raisonnée et de recettes de valorisation, pour diminuer fortement les pertes alimentaires sans alourdir la charge mentale domestique. Le texte insiste aussi sur l’équilibre nutritionnel en proposant des repères simples pour composer l’assiette, varier les sources de protéines, renforcer la place des légumineuses et des végétaux, et limiter les produits très transformés sans logique de restriction irréaliste. Enfin, la ressource propose un cadre d’évaluation continue basé sur des indicateurs lisibles — part de produits locaux et de saison, montant estimé du gaspillage, nombre de repas anti-gaspillage, évolution du panier moyen et coût par repas — pour ajuster les choix mois après mois. L’objectif global est de rendre la consommation responsable praticable, stable et mesurable, en conciliant santé, budget, environnement et soutien aux filières agricoles locales dans une logique de progrès concret plutôt que de perfection immédiate.',
                'steps' => [
                    'Étape 1 — Diagnostiquer ses habitudes : analyser tickets de caisse, déchets alimentaires et fréquence des achats impulsifs.',
                    'Étape 2 — Définir des objectifs mesurables : budget hebdo, part locale/saison, réduction des déchets, équilibre nutritionnel.',
                    'Étape 3 — Planifier les menus : organiser 5 à 7 repas avec variantes selon promotions et disponibilité saisonnière.',
                    'Étape 4 — Construire une liste intelligente : produits de base, frais prioritaires, substitutions possibles, quantités adaptées.',
                    'Étape 5 — Acheter avec méthode : comparer prix au kilo, lire les étiquettes, arbitrer entre local, label, transformation et prix.',
                    'Étape 6 — Cuisiner et conserver efficacement : batch cooking, portions adaptées, conservation différenciée, congélation.',
                    'Étape 7 — Valoriser les restes : recettes anti-gaspillage et réemploi des surplus.',
                    'Étape 8 — Mesurer et ajuster chaque mois : suivi dépenses, qualité nutritionnelle, volume de déchets et satisfaction familiale.',
                ],
                'checklist' => [
                    'Objectifs hebdomadaires (budget + qualité + gaspillage) définis.',
                    'Menu de la semaine validé avec alternatives.',
                    'Liste de courses structurée par priorité et conservation.',
                    'Produits frais planifiés selon consommation réelle du foyer.',
                    'Plan “restes” prêt (2 recettes minimum).',
                    'Espace de stockage organisé (frigo, placards, congélation).',
                    'Suivi mensuel des dépenses et déchets activé.',
                ],
                'purchase_strategy' => [
                    'Utiliser la règle 60/30/10 : 60% produits bruts, 30% transformés utiles, 10% achats plaisir.',
                    'Prioriser produits de saison et filières locales lorsque le rapport qualité/prix est cohérent.',
                    'Alterner points d’achat : marché, ferme, coopérative, supermarché pour optimiser coût et diversité.',
                    'Prévoir une liste de substitutions (ex : légumineuses à la place de protéines plus coûteuses).',
                ],
                'label_reading' => [
                    'Vérifier l’origine réelle (pays de production et de transformation).',
                    'Distinguer label officiel, mention marketing et auto-déclaration.',
                    'Contrôler la liste d’ingrédients : simplicité, additifs, taux de sucre/sel/gras.',
                    'Comparer le prix au kilo ou au litre pour objectiver la décision.',
                ],
                'seasonal_planning' => [
                    'Automne/hiver : légumes racines, choux, légumineuses, plats mijotés.',
                    'Printemps : produits verts, herbes fraîches, transition vers salades composées.',
                    'Été : fruits/légumes frais, conservation courte, plats froids et hydratation.',
                    'Prévoir une “base garde-manger” toute l’année (céréales, conserves utiles, épicerie sèche).',
                ],
                'anti_waste_playbook' => [
                    'Instaurer un “repas frigo” hebdomadaire pour écouler les produits fragiles.',
                    'Étiqueter les restes avec date et portion.',
                    'Transformer les surplus (soupes, quiches, compotes, sauces, pickles).',
                    'Ajuster les portions en fonction de l’appétit réel du foyer.',
                    'Composter les biodéchets non consommables quand possible.',
                ],
                'nutrition_balance' => [
                    'Répartir l’assiette : 1/2 végétaux, 1/4 féculents, 1/4 protéines.',
                    'Favoriser fibres et légumineuses pour un meilleur rapport nutrition/prix.',
                    'Limiter les produits ultra-transformés à fréquence encadrée.',
                    'Varier les sources de protéines (animales et végétales).',
                ],
                'budget_optimisation' => [
                    'Comparer prix au kilo systématiquement sur les familles de produits récurrentes.',
                    'Acheter en volume raisonné uniquement pour les produits stables.',
                    'Mutualiser certains achats via groupes d’achat ou commandes collectives.',
                    'Suivre 3 indicateurs mensuels : panier moyen, coût par repas, taux de gaspillage.',
                ],
                'kpi_tracking' => [
                    'Part de produits de saison dans le panier (%).',
                    'Part de produits locaux ou circuits courts (%).',
                    'Montant mensuel gaspillé estimé (€).',
                    'Nombre de repas anti-gaspillage réalisés.',
                    'Évolution du coût moyen par repas.',
                ],
            ],
            [
                'id' => 'calendrier-marches-locaux',
                'title' => 'Calendrier des marchés locaux',
                'description' => 'Repérer les marchés de producteurs et points de vente à la ferme.',
                'overview' => 'Référentiel pratique pour organiser ses achats locaux selon les jours, les saisons et les horaires des marchés.',
                'for' => 'Habitants, nouveaux arrivants, collectivités locales.',
                'continuous_content' => 'Cette page est développée comme un mode d’emploi complet pour organiser durablement ses achats en circuits courts grâce aux marchés locaux et à la vente directe à la ferme. Elle propose d’abord une méthode de cartographie précise des points d’approvisionnement : marchés hebdomadaires, marchés saisonniers, fermes avec horaires fixes, points-relais, foires agricoles et événements ponctuels, afin de visualiser une offre réellement mobilisable selon les lieux de vie et de travail. La ressource insiste ensuite sur la construction d’un calendrier d’achat réaliste, fondé sur les créneaux disponibles, les temps de déplacement, la capacité de stockage à domicile et les habitudes de consommation du foyer, pour passer d’une logique opportuniste à une routine régulière et prévisible. Le contenu guide également l’identification de producteurs référents par catégorie de produits (fruits et légumes, produits laitiers, viande, pain, transformés fermiers), en recommandant de vérifier la saisonnalité, la provenance, les modes de production, les volumes disponibles et la stabilité des prix au fil de l’année. Une partie importante est consacrée à l’arbitrage budgétaire : comparer les coûts réels sur des paniers types, planifier des rotations entre plusieurs lieux d’achat, anticiper les semaines de forte consommation et éviter les achats de dépannage plus coûteux. La page détaille aussi la façon d’anticiper les imprévus, par exemple en préparant un plan B lorsque le marché habituel est annulé, en conservant une liste de substitutions saisonnières et en coordonnant les achats avec un voisinage ou un groupe local pour sécuriser l’accès à certains produits. Dans une logique collective, la ressource montre comment partager le calendrier avec des familles, des associations ou des collectivités pour améliorer la visibilité des producteurs, soutenir l’économie locale et renforcer la résilience alimentaire territoriale. Enfin, elle recommande un suivi simple mais régulier — fréquence des visites, diversité des produits achetés, part du budget orientée vers le local, satisfaction des ménages — afin d’ajuster l’organisation et d’ancrer durablement des pratiques d’achat de proximité.',
                'steps' => [
                    'Lister les marchés hebdomadaires autour du domicile ou du lieu de travail.',
                    'Repérer les marchés saisonniers, foires agricoles et journées portes ouvertes.',
                    'Identifier les producteurs vendant en direct et leurs spécialités.',
                    'Prévoir une rotation de lieux d’achat pour lisser budget et diversité.',
                    'Partager le calendrier avec voisins, amis ou associations de quartier.',
                ],
                'checklist' => [
                    'Trois marchés de proximité identifiés.',
                    'Créneaux compatibles avec l’agenda personnel.',
                    'Contacts producteurs enregistrés.',
                    'Alternative prévue en cas d’absence d’un marché.',
                ],
            ],
            [
                'id' => 'aides-accompagnement',
                'title' => 'Aides et accompagnement',
                'description' => 'Comprendre les dispositifs d’appui à la transition agroécologique.',
                'overview' => 'Guide exhaustif pour identifier, préparer, déposer et suivre des demandes d’aides agricoles (investissement, transition, diversification, énergie, formation, accompagnement collectif), avec une logique pas-à-pas.',
                'for' => 'Agriculteurs en activité, jeunes installés, porteurs de projet, CUMA, coopératives, collectivités, structures de conseil et associations rurales.',
                'continuous_content' => 'Cette page est développée comme un guide exhaustif de montage et de pilotage des aides agricoles, conçu pour sécuriser un projet depuis l’idée initiale jusqu’à la clôture administrative et technique. Elle commence par un cadrage stratégique du besoin en aidant le porteur à formuler un objectif clair, mesurable et priorisé — modernisation, transition agroécologique, diversification, performance énergétique, transformation ou action collective — afin d’éviter les dossiers trop larges ou imprécis. La ressource détaille ensuite le diagnostic de départ indispensable, en combinant état technique de l’exploitation, situation économique, contraintes réglementaires, disponibilité foncière, capacités humaines et risques opérationnels, pour vérifier la faisabilité avant tout engagement. Elle accompagne pas à pas la cartographie des dispositifs mobilisables, en distinguant les guichets régionaux, européens, territoriaux et professionnels, puis en expliquant comment comparer les critères d’éligibilité, les calendriers, les plafonds de dépenses, les exigences documentaires et les conditions de versement. Une partie centrale est consacrée au montage financier : construction d’un budget réaliste poste par poste, collecte et comparaison de devis, plan de financement équilibré entre aides, emprunt, autofinancement et trésorerie, ainsi qu’anticipation des décalages de paiement pour éviter les tensions de liquidité. Le texte insiste fortement sur la qualité du dossier administratif, avec méthode de vérification des pièces, relecture de conformité, justification des impacts attendus et formalisation d’indicateurs de résultats, afin de renforcer la crédibilité de la demande et de réduire les allers-retours en instruction. La page explique aussi les points de vigilance critiques après dépôt : règles de démarrage des dépenses, traçabilité des preuves, archivage, gestion des avenants, suivi des jalons, préparation des contrôles et production d’un reporting cohérent avec les engagements initiaux. En complément, elle propose une logique de gestion des risques (retards, surcoûts, refus partiel, changement de contexte), avec des scénarios d’ajustement pour maintenir la viabilité du projet. L’objectif final est de transformer une demande d’aide en démarche de pilotage complète, robuste et documentée, utile autant pour les exploitants que pour les structures d’accompagnement qui souhaitent maximiser la réussite et l’impact réel des investissements soutenus.',
                'steps' => [
                    'Étape 1 — Clarifier le besoin : définir précisément le projet (modernisation, conversion, diversification, irrigation, sobriété énergétique, transformation à la ferme, etc.).',
                    'Étape 2 — Diagnostiquer le point de départ : établir un état initial (technique, économique, environnemental, social) avec des indicateurs mesurables.',
                    'Étape 3 — Cartographier les guichets : lister les financeurs et accompagnateurs possibles (région, commune, intercommunale, organismes professionnels, dispositifs européens, appels à projets).',
                    'Étape 4 — Vérifier l’éligibilité : comparer les critères du dispositif (profil du demandeur, taille de l’exploitation, zone géographique, nature des dépenses, délais).',
                    'Étape 5 — Construire le plan d’investissement : détailler postes de dépenses, devis, calendrier de réalisation et modalités de financement complémentaires.',
                    'Étape 6 — Préparer les pièces administratives : identité juridique, attestations, données économiques, éléments fonciers, preuves de conformité réglementaire.',
                    'Étape 7 — Formaliser les impacts attendus : gains de performance, réduction des consommations, amélioration de revenu, effets sur biodiversité/eau/sol/climat.',
                    'Étape 8 — Déposer la demande dans les délais : vérifier signatures, annexes, format attendu et accusé de réception.',
                    'Étape 9 — Sécuriser la mise en œuvre : lancer les dépenses uniquement selon les règles du dispositif et archiver toutes les preuves.',
                    'Étape 10 — Assurer le suivi et le reporting : documenter l’avancement, transmettre les justificatifs, préparer les contrôles et l’évaluation finale.',
                ],
                'checklist' => [
                    'Objectif principal du projet formulé en une phrase claire.',
                    'Budget prévisionnel complet (HT/TTC) avec devis datés et comparables.',
                    'Plan de financement équilibré (aides, emprunt, autofinancement, trésorerie).',
                    'Critères d’éligibilité validés point par point.',
                    'Dossier administratif complet et relu avant dépôt.',
                    'Calendrier des jalons (dépôt, instruction, décision, démarrage, clôture) validé.',
                    'Procédure d’archivage des pièces (numérique + papier) en place.',
                    'Indicateurs de résultats définis avant démarrage.',
                    'Référent technique/administratif identifié dans l’équipe ou l’accompagnement.',
                    'Plan de gestion des risques (retard travaux, surcoûts, refus partiel, contrôle) préparé.',
                ],
                'eligible_projects' => [
                    'Investissements de modernisation (matériel, bâtiments, sécurité, ergonomie).',
                    'Transition agroécologique (sols, biodiversité, intrants, eau, autonomie fourragère).',
                    'Performance énergétique (isolation, efficacité, production d’énergie renouvelable).',
                    'Diversification et transformation (ateliers de transformation, vente directe, nouveaux débouchés).',
                    'Innovation et numérique (outils d’aide à la décision, capteurs, traçabilité).',
                    'Actions collectives (mutualisation, coopération territoriale, formations de groupe).',
                ],
                'required_documents' => [
                    'Pièce d’identité et statuts/forme juridique de la structure.',
                    'Numéros administratifs de l’exploitation et attestations à jour.',
                    'Bilans/comptes de résultat récents ou prévisionnels pour les porteurs de projet.',
                    'Devis détaillés, plans, descriptifs techniques et calendrier des travaux.',
                    'Justificatifs fonciers (propriété, bail, autorisations) selon le projet.',
                    'Attestations de conformité réglementaire (urbanisme, environnement, sécurité).',
                    'Note de motivation précisant objectifs, impacts et cohérence territoriale.',
                ],
                'timeline' => [
                    'Semaine 1-2 : cadrage du besoin et collecte d’informations.',
                    'Semaine 3-6 : montage technique et financier du dossier.',
                    'Semaine 7-8 : relecture externe et dépôt.',
                    'Mois 3-6 : phase d’instruction et éventuelles demandes de compléments.',
                    'Après accord : lancement opérationnel, suivi des dépenses et reporting.',
                ],
                'common_pitfalls' => [
                    'Dépenses engagées avant l’accord, rendant certaines lignes inéligibles.',
                    'Dossier incomplet ou non conforme au format demandé.',
                    'Objectifs trop vagues, sans indicateurs mesurables.',
                    'Sous-estimation des délais administratifs et techniques.',
                    'Absence de plan de trésorerie pour absorber les avances de dépenses.',
                ],
                'support_contacts' => [
                    'Guichets agricoles régionaux : orientation sur les appels ouverts et l’éligibilité.',
                    'Centres de gestion et conseillers technico-économiques : sécurisation du business plan.',
                    'Structures locales de développement rural : articulation avec les projets de territoire.',
                    'Réseaux professionnels agricoles : retours d’expérience et mutualisation des bonnes pratiques.',
                ],
            ],
            [
                'id' => 'decouvrir-labels',
                'title' => 'Découvrir les labels',
                'description' => 'Comparer les principaux labels qualité, origine et durabilité.',
                'overview' => 'Clés de lecture pour comprendre les labels alimentaires et éviter les confusions entre origine, qualité sanitaire et impact environnemental.',
                'for' => 'Consommateurs, animateurs d’ateliers, structures éducatives.',
                'continuous_content' => 'Cette page est développée comme un guide exhaustif de lecture des labels alimentaires, afin d’aider les citoyens à distinguer clairement ce qui relève d’une certification vérifiable, d’une indication d’origine, d’un engagement environnemental encadré ou d’un simple argument marketing. Elle propose une démarche structurée en plusieurs temps : identifier la promesse exacte portée par le label, vérifier le cadre de contrôle indépendant, comprendre le niveau d’exigence du cahier des charges, puis comparer des produits similaires avec des critères constants pour éviter les décisions biaisées. La ressource insiste sur la nécessité de lire simultanément plusieurs informations présentes sur l’emballage — origine de production, lieu de transformation, composition, degré de transformation, prix au kilo, saisonnalité — car aucun logo, pris isolément, ne suffit à qualifier l’impact global d’un produit. Elle explique aussi les confusions fréquentes entre labels officiels, mentions privées et vocabulaire marketing valorisant, en donnant une méthode concrète pour repérer les preuves tangibles et écarter les messages ambigus. Une partie pédagogique est dédiée aux arbitrages réalistes du quotidien : comment concilier budget, qualité nutritionnelle, impact environnemental et soutien aux filières locales, sans viser une perfection impossible ni tomber dans la surcharge d’information. La page propose en complément des repères d’animation pour ateliers, écoles et actions de sensibilisation, afin de transformer la lecture d’étiquettes en compétence pratique transférable. Enfin, elle recommande de formaliser une grille personnelle de décision — critères prioritaires, seuils de prix acceptables, points non négociables — pour rendre les achats plus cohérents dans le temps. L’objectif est de passer d’une consommation guidée par des impressions à une consommation éclairée, argumentée et stable, fondée sur des informations vérifiables et une stratégie d’achat assumée.',
                'steps' => [
                    'Identifier la promesse du label : origine, méthode de production, cahier des charges.',
                    'Vérifier la présence d’un organisme de contrôle indépendant.',
                    'Comparer plusieurs produits d’une même catégorie avec les mêmes critères.',
                    'Repérer les mentions marketing non certifiées pour éviter les biais.',
                    'Conserver une logique d’ensemble : label + saison + proximité + budget.',
                ],
                'checklist' => [
                    'Au moins trois labels compris et comparés.',
                    'Différence entre certification et argument marketing maîtrisée.',
                    'Critères personnels de choix formalisés.',
                    'Habitude d’achat alignée avec ces critères.',
                ],
            ],
            [
                'id' => 'boite-a-outils-anti-gaspillage',
                'title' => 'Boîte à outils anti-gaspillage',
                'description' => 'Astuces pour mieux conserver, cuisiner et valoriser les produits frais.',
                'overview' => 'Boîte à outils opérationnelle pour réduire les pertes alimentaires à la maison et mieux valoriser chaque produit.',
                'for' => 'Familles, étudiants, cuisines collectives, associations.',
                'continuous_content' => 'Cette page est développée comme une boîte à outils exhaustive pour réduire durablement le gaspillage alimentaire, que ce soit dans un foyer, une cuisine collective, une colocation, une association ou un petit service de restauration. Elle commence par une méthode de diagnostic précise, en invitant à mesurer les pertes réelles par catégorie de produits (fruits/légumes, produits laitiers, pain, plats préparés, restes de repas), afin d’identifier les points de fuite prioritaires plutôt que d’appliquer des solutions générales peu efficaces. La ressource propose ensuite une organisation structurée des stocks : classement des aliments selon leur fragilité, règles de rotation FIFO, visibilité des dates limites, zones de consommation rapide dans le réfrigérateur et planification d’achats compatibles avec la capacité réelle de stockage. Le texte détaille aussi les bonnes pratiques de conservation, avec des repères concrets pour la chaîne du froid, l’étiquetage des contenants, la congélation en portions adaptées, la décongélation sécurisée et la prolongation de la durée de vie des denrées sans compromettre la qualité sanitaire. Une part importante est consacrée à la valorisation culinaire des surplus, à travers une logique de recettes de récupération, de batch cooking ajusté, de menus de fin de semaine et de réemploi intelligent des restes, pour transformer les excédents en repas attractifs plutôt qu’en déchets. La page aborde également l’optimisation économique, en reliant chaque geste anti-gaspillage à des indicateurs de budget (coût des pertes évitées, coût par repas, meilleure utilisation des produits achetés) afin de rendre visibles les gains concrets. Dans une perspective environnementale, elle rappelle l’impact de la réduction des biodéchets sur les ressources mobilisées en amont (eau, énergie, travail agricole, transport, emballage) et propose des solutions de fin de cycle comme le compostage lorsque cela est possible. Enfin, la ressource recommande un pilotage mensuel simple mais rigoureux — volume de déchets alimentaires, fréquence de valorisation des restes, taux d’utilisation des produits frais — pour ancrer des habitudes stables dans le temps. L’objectif est de passer d’actions ponctuelles à une véritable stratégie anti-gaspillage continue, mesurable et facilement reproductible.',
                'steps' => [
                    'Classer les aliments selon leur sensibilité (très périssable, moyen, longue conservation).',
                    'Adopter la règle FIFO (premier entré, premier sorti) dans le frigo et les placards.',
                    'Programmer une “recette de récupération” hebdomadaire.',
                    'Congeler intelligemment avec portions, dates et étiquettes.',
                    'Composter les biodéchets non consommables quand c’est possible.',
                ],
                'checklist' => [
                    'Inventaire hebdomadaire du frigo réalisé.',
                    'Restes valorisés au moins une fois par semaine.',
                    'Plan de conservation affiché en cuisine.',
                    'Volume de déchets alimentaires suivi mensuellement.',
                ],
            ],
            [
                'id' => 'parcours-pedagogiques',
                'title' => 'Parcours pédagogiques',
                'description' => 'Ressources pour enseignants et familles autour de l’alimentation et des saisons.',
                'overview' => 'Parcours d’apprentissage progressifs (primaire, secondaire, famille) autour de l’alimentation, des saisons et des métiers agricoles.',
                'for' => 'Enseignants, éducateurs, parents et médiateurs scientifiques.',
                'continuous_content' => 'Cette page est développée comme un dispositif pédagogique exhaustif pour construire des parcours d’apprentissage cohérents autour de l’alimentation, des saisons et des réalités agricoles, depuis l’initiation jusqu’à un niveau d’analyse plus avancé. Elle propose une progression complète qui aide d’abord à définir les objectifs éducatifs par tranche d’âge, puis à organiser des séquences structurées alternant apports de connaissances, observation du réel, activités pratiques, débats guidés et restitution des acquis. La ressource insiste sur l’adaptation des contenus aux publics visés — école primaire, secondaire, familles, médiation scientifique — afin d’ajuster le vocabulaire, la durée, le niveau d’abstraction et les formats d’activité, tout en conservant un fil pédagogique commun. Le texte détaille la méthode de conception pas à pas : choix d’un thème central (saisonnalité, circuit alimentaire, métiers, biodiversité, gaspillage), formulation de questions d’enquête, sélection de supports (fiches, vidéos, données simples, ressources locales), préparation d’ateliers expérientiels et définition de critères d’évaluation lisibles. Une attention particulière est portée à l’articulation entre théorie et terrain, avec des recommandations pour intégrer visites, observations directes, rencontres d’acteurs et mini-projets qui rendent l’apprentissage concret et mémorable. La page propose aussi des modalités de restitution variées — affiches, capsules audio, exposés, quiz, journaux de bord — permettant de valoriser les productions des participants et de renforcer l’appropriation des contenus. Dans une logique de pilotage éducatif, elle invite à mesurer l’évolution des connaissances, des compétences et des attitudes, puis à capitaliser les retours pour améliorer chaque nouvelle édition du parcours. Elle constitue ainsi une base robuste, réutilisable et modulable pour les enseignants, éducateurs et parents qui souhaitent déployer des démarches pédagogiques durables, actives et ancrées dans les enjeux alimentaires et agricoles contemporains.',
                'steps' => [
                    'Choisir un niveau (débutant, intermédiaire, avancé) selon l’âge des participants.',
                    'Structurer le parcours en séquences courtes : comprendre, observer, pratiquer, restituer.',
                    'Combiner supports : vidéos courtes, fiches, expériences simples et sortie terrain.',
                    'Évaluer les acquis avec un mini-projet (affiche, capsule audio, quiz).',
                    'Capitaliser les résultats pour réutilisation l’année suivante.',
                ],
                'checklist' => [
                    'Objectifs pédagogiques explicités.',
                    'Supports et activités adaptés à l’âge.',
                    'Moment de restitution prévu.',
                    'Évaluation finale simple préparée.',
                ],
            ],
        ],
    ];
}
